#!/usr/bin/env python3
"""Single source of truth for the sigma-delta modulator design values.

Every simulation tier derives its numbers from this file:
  - tier 0 (python model) imports it directly
  - tier 1/2 (ngspice) include spice/params.spice, generated by running this file

Design equations (see DESIGN.md):
  loop coefficient   k    = feedback charge per cycle / CINT, referred to volts
  feedback charge    Qfb  = (VREFP - VCM) / RDAC * (TS/2)     [RZ, half-period pulse]
  input full scale   FSIN = Qfb * RIN / TS = (VREFP-VCM)/2 * RIN/RDAC
"""

# --- clock ---------------------------------------------------------------
FS   = 50e6            # modulator clock [Hz] (open item: verify TT mux limit)
TS   = 1 / FS          # clock period [s]
TR   = 0.2e-9          # clock rise/fall time [s]
PWH  = TS / 2 - TR     # clock high time [s] (50% duty)

# --- references (3.3 V single-ended core) --------------------------------
VCM   = 1.65           # analog mid-rail [V]
VREFP = 2.15           # DAC high reference [V]
VREFN = 1.15           # DAC low reference [V]

# --- loop passives -------------------------------------------------------
RIN  = 40e3            # input resistor [ohm]
RDAC = 20e3            # feedback DAC resistor [ohm]
CINT = 1e-12           # integration capacitor [F]
AOL  = 1e4             # tier-1 ideal OTA open-loop gain (80 dB)

# derived, for reference
K_FB   = (VREFP - VCM) / RDAC * (TS / 2) / CINT   # integrator step per cycle [V] = 0.25
FS_IN  = (VREFP - VCM) / 2 * RIN / RDAC           # input full scale [V] = +-0.5 around VCM

# --- test stimulus (coherent FFT) ----------------------------------------
NFFT    = 4096         # analysis window [clock cycles]
NSETTLE = 256          # discarded startup cycles
SIG_BIN = 5            # input at FFT bin 5 (odd, inside OSR=250 band edge bin 8)
FIN     = SIG_BIN * FS / NFFT                     # 61.035 kHz
AMP     = 0.3          # input amplitude [V] (-4.4 dBFS)

# --- transient control ---------------------------------------------------
TSTEP = 0.5e-9
TSTOP = (NFFT + NSETTLE) * TS

# decimation paths (analysis only, lives on the FPGA)
OSR_FAST = 25          # ~1 MHz bandwidth
OSR_PREC = 250         # ~100 kHz bandwidth


def emit(path="spice/params.spice"):
    import os
    os.makedirs(os.path.dirname(path), exist_ok=True)
    names = ["FS", "TS", "TR", "PWH", "VCM", "VREFP", "VREFN",
             "RIN", "RDAC", "CINT", "AOL", "FIN", "AMP", "TSTEP", "TSTOP"]
    with open(path, "w") as f:
        f.write("* GENERATED by params.py -- do not edit\n")
        for n in names:
            f.write(f".param {n}={globals()[n]:.6g}\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    emit()
