#!/usr/bin/env python3
"""Bias generator (tier 2, sky130 5V devices, 3.3 V): replaces the OTA's
ideal IREFP/IREFN/VBNC/VBPC sources.

Topology: constant-gm (beta-multiplier) core -- NMOS diode M1 vs K-wide M2
degenerated by RB, PMOS mirror on top -- so the master current is set by
RB and a geometry ratio, and every derived quantity is either a current
mirror ratio or a resistor RATIO:
  IREFP sink  = 19 x master (380 uA into the OTA's PMOS-diode pin)
  IREFN source= 17 x master (340 uA into the OTA's NMOS-diode pin)
  VBNC = master x R_BNC (1.5 V), VBPC = master x R_BPC (0.5 V) -- both
  R/RB ratios, first-order flat over process/temperature.
Startup: weak long-L PMOS leaker into the NMOS mirror gate (few hundred
nA, <2% of master); its error is included in everything measured here.

Resistors are ideal in this testbench (the layout will use the same
high-res poly as RIN/RDAC; absolute tolerance moves the master current
but not the resistor-ratio bias voltages).

Measurements:
  1. Operating point across corners and VDD +-10%: master current, both
     reference currents, VBNC/VBPC.
  2. Startup: VDD ramp 0->3.3 V, verify the core leaves the zero state
     and settles.
  3. Acceptance: the golden OTA netlist (spice/ota_top.spice, run `make
     xcheck` first) re-measured with the REAL bias block vs ideal
     sources: A0/GBW/PM must track within tolerance.

Usage: python3 sim/bias_tb.py    (sizes in BSIZES below)
Writes reports/results/bias.json.
"""

import json
import os
import re
import subprocess
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.ota_tb import SIZES as OTA_S, PDK_LIB, WUNIT
from tools.gen_layout_cells import RHO, WRES, CAREA, CPERI

NF = "sky130_fd_pr__nfet_g5v0d10v5"
PF = "sky130_fd_pr__pfet_g5v0d10v5"
RES, CAP = "sky130_fd_pr__res_high_po_1p41", "sky130_fd_pr__cap_mim_m3_1"

LAYOUT = False   # --layout: emit real poly-R / MiM devices in the subckt


# ngspice model calibration (tt, pinned PDK): R = REND + RPUM * L.
# Measured 2026-07-19 by op on L=10/100/330.7 -- the model carries a
# 256 ohm end resistance that magic's sheet-rho extraction (RHO=319.8)
# does not, so lengths are calibrated against the MODEL (silicon truth);
# magic-extracted ohms will read ~5-10% high on short Rs, which is
# informational only (LVS compares geometry, not ohms).
REND, RPUM = 256.2, 230.06


def res_geom(r):
    """(nx, segment_l, total_drawn_l) of a res_high_po_1p41 snake for
    target R (ngspice-model calibrated; R must exceed REND -- no
    sub-260-ohm poly Rs). Segment length lands on the 0.005 um grid so
    the golden L and the drawn layout agree by construction."""
    assert r > REND + 50, f"target {r} below realizable minimum"
    ltot = (r - REND) / RPUM
    nx = max(1, round(ltot / 20))          # ~20 um segments
    seg = round(ltot / nx / 0.005) * 0.005
    return nx, round(seg, 3), round(nx * seg, 3)


def r_len(r):
    """Drawn total length for target R (see res_geom)."""
    return res_geom(r)[2]


def c_side(c):
    """Side of a square cap_mim_m3_1 for target C [F]."""
    cf = c * 1e15
    import math
    return round((-4 * CPERI + math.sqrt(16 * CPERI**2
                                         + 4 * CAREA * cf)) / (2 * CAREA), 2)


def r_card(name, a, b, r):
    return f"X{name} {a} {b} VSS {RES} L={r_len(r):g} mult=1 m=1"


def c_card(name, a, b, c):
    s = c_side(c)
    return f"X{name} {a} {b} {CAP} W={s:g} L={s:g} m=1"

BSIZES = dict(
    W_N=10, L_N=1.0,      # M1 NMOS diode (M2 = K x W_N)
    K=4,                  # beta-multiplier ratio
    RB=4.6e3,             # sets master ~20 uA (trimmed at tt, post startup-disable)
    W_P=10, L_P=1.0,      # PMOS mirror unit
    M_IREFP=19,           # sink mirror ratio  -> 380 uA
    M_IREFN=17,           # source mirror ratio-> 340 uA
    R_BNC=75e3,           # VBNC = Im x R_BNC = 1.5 V
    R_BPC=25e3,           # VBPC = Im x R_BPC = 0.5 V
    W_START=5, L_START=50,  # startup leaker
)


def m(w):
    return max(1, round(w / WUNIT))


def bias_subckt(p, layout=None):
    if layout is None:
        layout = LAYOUT
    if layout:
        rb = r_card("RB", "rs", "VSS", p["RB"])
        rbnc = r_card("RBNC", "vbnc_i", "VSS", p["R_BNC"])
        rbpc = r_card("RBPC", "vbpc_i", "VSS", p["R_BPC"])
        rnb1 = r_card("RNB1", "vbnc_i", "VBNC", 1e3)
        rnb2 = r_card("RNB2", "vbpc_i", "VBPC", 1e3)
    else:
        rb = f"RB rs VSS {p['RB']}"
        rbnc = f"RBNC vbnc_i VSS {p['R_BNC']}"
        rbpc = f"RBPC vbpc_i VSS {p['R_BPC']}"
        rnb1 = "RNB1 vbnc_i VBNC 1k"
        rnb2 = "RNB2 vbpc_i VBPC 1k"
    return f"""
.subckt bias IREFP IREFN VBNC VBPC VDD VSS
* constant-gm core: M1 diode vs K-wide degenerated M2, PMOS mirror top
XM1 nb nb VSS VSS {NF} W={WUNIT} L={p['L_N']} nf=1 m={m(p['W_N'])}
XM2 pb nb rs VSS {NF} W={WUNIT} L={p['L_N']} nf=1 m={m(p['K'] * p['W_N'])}
{rb}
XMP1 nb pb VDD VDD {PF} W={WUNIT} L={p['L_P']} nf=1 m={m(p['W_P'])}
XMP2 pb pb VDD VDD {PF} W={WUNIT} L={p['L_P']} nf=1 m={m(p['W_P'])}
* startup with disable: the leaker feeds nst; while the core is off
* (vbnc_i = 0) the always-on PMOS pass XFD conducts nst -> nb and kicks
* the loop; once running, XSW (gate = vbnc_i = 1.5 V) yanks nst to VSS,
* XFD's source drops below |Vtp| and the leaker is fully stolen away
* (first pass measured the always-on leaker at ~3.4 uA = 17% master
* error -- Vsg is 2.45 V, not the subthreshold trickle assumed)
XST nst VSS VDD VDD {PF} W={WUNIT} L={p['L_START']} nf=1 m=1
XSW nst vbnc_i VSS VSS {NF} W={WUNIT} L=0.5 nf=1 m=2
XFD nb VSS nst VDD {PF} W={WUNIT} L=2 nf=1 m=1
* reference-current mirrors, cascoded with the block's own VBNC/VBPC
* (5V devices at L=1 have soft saturation; uncascoded, IREFP ran 43% hot
* and tracked VDD -- measured, first pass)
XIP ipd nb VSS VSS {NF} W={WUNIT} L={p['L_N']} nf=1 m={m(p['M_IREFP'] * p['W_N'])}
XIPC IREFP vbnc_i ipd VSS {NF} W={WUNIT} L=0.5 nf=1 m={m(p['M_IREFP'] * p['W_N'])}
XIN ind pb VDD VDD {PF} W={WUNIT} L={p['L_P']} nf=1 m={m(p['M_IREFN'] * p['W_P'])}
XINC IREFN vbpc_i ind VDD {PF} W={WUNIT} L=0.5 nf=1 m={m(p['M_IREFN'] * p['W_P'])}
* cascode gate biases: master current into resistor strings (R ratios);
* RNB isolation Rs are 1k (100 was below the poly end-resistance floor
* of ~260 ohm; pure RC isolation, no DC -- value non-critical)
XVN vbnc_i pb VDD VDD {PF} W={WUNIT} L={p['L_P']} nf=1 m={m(p['W_P'])}
{rbnc}
XVP vbpc_i pb VDD VDD {PF} W={WUNIT} L={p['L_P']} nf=1 m={m(p['W_P'])}
{rbpc}
{rnb1}
{rnb2}
* VBNC/VBPC 1 pF MiM filter caps live OUTSIDE this subckt (top-level
* cells, same class as the reference decaps -- MiM plates route on
* m3/m4, above this block's m1/m2/m3 router)
.ends
"""


def bias_caps(vbnc="vbnc", vbpc="vbpc", layout=None):
    """The top-level VBNC/VBPC filter caps (TB + top assembly)."""
    if layout is None:
        layout = LAYOUT
    if layout:
        return (c_card("CBN", vbnc, "0", 1e-12) + "\n"
                + c_card("CBP", vbpc, "0", 1e-12))
    return f"CBN {vbnc} 0 1p\nCBP {vbpc} 0 1p"


def ota_golden():
    txt = open("spice/ota_top.spice").read()
    mm = re.search(r"^\.subckt ota .*?^\.ends\b", txt, re.M | re.S)
    if not mm:
        sys.exit("spice/ota_top.spice missing -- run `make xcheck` first")
    return mm.group(0)


def run(deck, name):
    open(f"spice/{name}.spice", "w").write(deck)
    r = subprocess.run(["ngspice", "-b", f"{name}.spice"], cwd="spice",
                      capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-1200:])
        sys.exit(1)


def op_point(p, corner, vdd):
    deck = f"""* bias op ({corner}, VDD={vdd})
.lib {PDK_LIB} {corner}
{bias_subckt(p)}
VDD vdd 0 {vdd}
* loads mimic the OTA diode pins
XDP irefp irefp vdd vdd {PF} W={WUNIT} L={OTA_S['L_TAIL']} nf=1 m={m(OTA_S['W_TAIL'])}
XDN irefn irefn 0 0 {NF} W={WUNIT} L={OTA_S['L_SINK']} nf=1 m={m(OTA_S['W_SINK'])}
XB irefp irefn vbnc vbpc vdd 0 bias
{bias_caps()}
.control
op
wrdata bias_op.csv i(VDD) v(vbnc) v(vbpc) v(irefp) v(irefn) v(xb.nb) v(xb.rs)
.endc
.end
"""
    run(deck, "bias_op")
    d = np.loadtxt("spice/bias_op.csv")
    # currents via the diode loads: recompute from the mirror node values
    # is fiddly; report VBNC/VBPC and total supply current, and measure
    # the two references directly with 0 V sense sources instead
    deck2 = deck.replace("XB irefp irefn vbnc vbpc vdd 0 bias",
                         "XB irefp_s irefn_s vbnc vbpc vdd 0 bias\n"
                         "VSP irefp_s irefp 0\nVSN irefn_s irefn 0")
    deck2 = deck2.replace("wrdata bias_op.csv i(VDD) v(vbnc) v(vbpc) "
                          "v(irefp) v(irefn) v(xb.nb) v(xb.rs)",
                          "wrdata bias_op.csv i(VSP) i(VSN) v(vbnc) v(vbpc)")
    run(deck2, "bias_op")
    d = np.loadtxt("spice/bias_op.csv")
    return dict(irefp_ua=abs(d[1]) * 1e6, irefn_ua=abs(d[3]) * 1e6,
                vbnc=d[5], vbpc=d[7])


def startup(p):
    deck = f"""* bias startup (VDD ramp)
.lib {PDK_LIB} tt
{bias_subckt(p)}
VDD vdd 0 PWL(0 0 1u 3.3 20u 3.3)
XDP irefp irefp vdd vdd {PF} W={WUNIT} L={OTA_S['L_TAIL']} nf=1 m={m(OTA_S['W_TAIL'])}
XDN irefn irefn 0 0 {NF} W={WUNIT} L={OTA_S['L_SINK']} nf=1 m={m(OTA_S['W_SINK'])}
XB irefp irefn vbnc vbpc vdd 0 bias
{bias_caps()}
.tran 10n 20u uic
.control
run
wrdata bias_start.csv v(vbnc) v(vbpc)
.endc
.end
"""
    run(deck, "bias_start")
    d = np.loadtxt("spice/bias_start.csv")
    t, vbnc, vbpc = d[:, 0], d[:, 1], d[:, 3]
    settled = t > 15e-6
    ok = vbnc[settled].min() > 1.2 and vbpc[settled].min() > 0.35
    return dict(ok=bool(ok), vbnc_final=float(vbnc[-1]),
                vbpc_final=float(vbpc[-1]))


def ota_with_bias(p, corner="tt"):
    """A0/GBW/PM of the golden OTA with the real bias block."""
    deck = f"""* OTA + real bias acceptance
.lib {PDK_LIB} {corner}
{ota_golden()}
{bias_subckt(p)}
VDDA vdda 0 3.3
VCMA vcma 0 {OTA_S['VCM']}
VINA ina vcma DC 0 AC 1
LFB outa inma 1e6
CFB inma vcma 1e6
CLA outa 0 {OTA_S['CL']}
XB irefpa irefna vbnca vbpca vdda 0 bias
{bias_caps("vbnca", "vbpca")}
XA ina inma outa vdda 0 irefpa irefna vbnca vbpca ota
.control
op
ac dec 20 100 3g
wrdata bias_ota_ac.csv v(outa)
.endc
.end
"""
    run(deck, "bias_ota")
    ac = np.loadtxt("spice/bias_ota_ac.csv")
    f, h = ac[:, 0], ac[:, 1] + 1j * ac[:, 2]
    mag, ph = np.abs(h), np.unwrap(np.angle(h)) * 180 / np.pi
    a0 = 20 * np.log10(mag[0])
    i = np.argmax(mag < 1)
    ugf = 10 ** np.interp(0, [np.log10(mag[i]), np.log10(mag[i - 1])],
                          [np.log10(f[i]), np.log10(f[i - 1])])
    pm = 180 + np.interp(np.log10(ugf), np.log10(f), ph)
    return dict(a0_db=round(a0, 1), gbw_mhz=round(ugf / 1e6),
                pm_deg=round(pm))


def main():
    global LAYOUT
    if "--layout" in sys.argv:
        LAYOUT = True
        print("(layout netlist: real poly-R / MiM devices)")
    os.makedirs("spice", exist_ok=True)
    print(f"{'corner':>7s} {'VDD':>5s} {'IREFP':>8s} {'IREFN':>8s} "
          f"{'VBNC':>6s} {'VBPC':>6s}")
    ops = {}
    for corner in ("tt", "ss", "ff", "sf", "fs"):
        for vdd in (2.97, 3.3, 3.63) if corner == "tt" else (3.3,):
            o = op_point(BSIZES, corner, vdd)
            ops[f"{corner}/{vdd}"] = o
            print(f"{corner:>7s} {vdd:5.2f} {o['irefp_ua']:7.1f}u "
                  f"{o['irefn_ua']:7.1f}u {o['vbnc']:6.3f} {o['vbpc']:6.3f}")

    st = startup(BSIZES)
    print(f"startup: {'ok' if st['ok'] else 'FAIL'} "
          f"(VBNC {st['vbnc_final']:.3f} V, VBPC {st['vbpc_final']:.3f} V)")

    print(f"{'':>7s} {'A0':>8s} {'GBW':>8s} {'PM':>5s}")
    acc = {}
    for corner in ("tt", "ss", "ff"):
        a = ota_with_bias(BSIZES, corner)
        acc[corner] = a
        print(f"{corner:>7s} {a['a0_db']:7.1f}d {a['gbw_mhz']:5d}MHz "
              f"{a['pm_deg']:4d}d")
    ok = (st["ok"]
          and abs(acc["tt"]["a0_db"] - 65.2) < 2
          and abs(acc["tt"]["gbw_mhz"] - 209) < 40
          and acc["tt"]["pm_deg"] > 50)
    print("ACCEPT" if ok else "REJECT -- resize/tune")
    os.makedirs("reports/results", exist_ok=True)
    json.dump(dict(ok=bool(ok), op=ops, startup=st, ota=acc,
                   sizes={k: v for k, v in BSIZES.items()}),
              open("reports/results/bias.json", "w"), indent=1)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
