#!/usr/bin/env python3
"""sky130 3.3V FET characterization for the sigma-delta tier-2 design.

One batched ngspice run (the sky130 library parse dominates runtime) produces:
  1. gm/Id vs current density for nfet/pfet_g5v0d10v5 at L = 0.5/1/2 um
     -> OTA sizing curves (gm/Id methodology)
  2. Pass-switch ron vs passed voltage (NMOS gate=3.3, PMOS gate=0, and the
     parallel t-gate combo) -> reference-window decision (DESIGN.md item 6)

Writes reports/fet_char.html and prints the key numbers.

Usage: make char   (or python3 sim/char_fets.py from the repo root)
"""

import os
import subprocess
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.compare_dac import style_axes, fig_to_b64, C_SURF, C_TEXT, C_TEXT2

PDK_ROOT = os.environ.get("PDK_ROOT", "/home/nvme/pdk")
PDK_LIB = f"{PDK_ROOT}/sky130A/libs.tech/ngspice/sky130.lib.spice"
W = 10.0          # um, all characterization devices
LS = [0.5, 1.0, 2.0]
VDD = 3.3
RON_SENSE = 0.01  # V across the switch for the ron measurement
# ordinal blue ramp (dataviz reference palette, steps 250/450/650)
L_COLORS = ["#86b6ef", "#2a78d6", "#104281"]

DECK = f"""* sky130 3.3V FET characterization (generated by sim/char_fets.py)
.lib {PDK_LIB} tt
.param W={W}

* --- gm/Id: three L values share one swept gate, saturation Vds ---
Vgn gn 0 0
{chr(10).join(f"Vdn{i} dn{i} 0 1.65" + chr(10) +
              f"XN{i} dn{i} gn 0 0 sky130_fd_pr__nfet_g5v0d10v5 L={L} W={{W}} nf=1"
              for i, L in enumerate(LS))}

Vgp gp 0 0
Vddp vddp 0 {VDD}
{chr(10).join(f"Vdp{i} dp{i} 0 1.65" + chr(10) +
              f"XP{i} dp{i} gp vddp vddp sky130_fd_pr__pfet_g5v0d10v5 L={L} W={{W}} nf=1"
              for i, L in enumerate(LS))}

* --- pass-switch ron vs passed voltage, L=0.5 ---
Vpass vp 0 0
Vsw_n swn vp {RON_SENSE}
XSWN swn vgn3 vp 0 sky130_fd_pr__nfet_g5v0d10v5 L=0.5 W={{W}} nf=1
Vgn3 vgn3 0 {VDD}
Vsw_p swp vp {RON_SENSE}
XSWP swp 0 vp vddp sky130_fd_pr__pfet_g5v0d10v5 L=0.5 W={{W}} nf=1

.control
set wr_singlescale
set wr_vecnames
dc Vgn 0 {VDD} 0.005
wrdata char_nfet.csv {' '.join(f'i(Vdn{i})' for i in range(len(LS)))}
dc Vgp 0 {VDD} 0.005
wrdata char_pfet.csv {' '.join(f'i(Vdp{i})' for i in range(len(LS)))}
dc Vpass 0 3.1 0.01
wrdata char_ron.csv i(Vsw_n) i(Vsw_p)
.endc
.end
"""


def run_deck(workdir):
    deck = os.path.join(workdir, "char.spice")
    open(deck, "w").write(DECK)
    subprocess.run(["ngspice", "-b", "char.spice"], cwd=workdir,
                   check=True, capture_output=True)
    nf = np.loadtxt(os.path.join(workdir, "char_nfet.csv"), skiprows=1)
    pf = np.loadtxt(os.path.join(workdir, "char_pfet.csv"), skiprows=1)
    ron = np.loadtxt(os.path.join(workdir, "char_ron.csv"), skiprows=1)
    return nf, pf, ron


def vth_cc(vgs, idr, l):
    """Constant-current threshold: Vgs where Id = 1uA * W/L."""
    o = np.argsort(idr)
    icc = 1e-6 * W / l
    return float(np.interp(icc, idr[o], vgs[o]))


def gmid_panels(nf, pf):
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2), sharey=True)
    fig.patch.set_facecolor(C_SURF)
    for ax, dat, name, flip in ((axes[0], nf, "nfet_g5v0d10v5", False),
                                (axes[1], pf, "pfet_g5v0d10v5", True)):
        style_axes(ax)
        v = dat[:, 0]
        for i, (l, col) in enumerate(zip(LS, L_COLORS)):
            idr = np.abs(dat[:, 1 + i])
            vgs = (VDD - v) if flip else v
            o = np.argsort(vgs)
            vgs, idr = vgs[o], idr[o]
            gm = np.gradient(idr, vgs)
            sel = idr > 1e-9 * W          # ignore deep cutoff
            ax.semilogx(idr[sel] / W * 1e6, gm[sel] / idr[sel],
                        color=col, lw=1.8)
            ax.text(idr[sel][-1] / W * 1e6 * 0.5, gm[sel][-1] / idr[sel][-1] + 1.2,
                    f"L={l}", color=C_TEXT2, fontsize=8)
        ax.set_xlabel("Id/W [uA/um]", color=C_TEXT2, fontsize=9)
        ax.set_title(f"{name}, |Vds|=1.65 V", color=C_TEXT, fontsize=10,
                     loc="left")
        ax.set_ylim(0, 30)
    axes[0].set_ylabel("gm/Id [1/V]", color=C_TEXT2, fontsize=9)
    fig.tight_layout()
    return fig_to_b64(fig)


def ron_panel(ron):
    fig, ax = plt.subplots(figsize=(11, 4.2))
    fig.patch.set_facecolor(C_SURF)
    style_axes(ax)
    vp = ron[:, 0]
    rn = RON_SENSE / np.maximum(np.abs(ron[:, 1]), 1e-12)
    rp = RON_SENSE / np.maximum(np.abs(ron[:, 2]), 1e-12)
    rtg = 1.0 / (1.0 / rn + 1.0 / rp)
    ax.semilogy(vp, rn, color="#2a78d6", lw=1.8)
    ax.semilogy(vp, rp, color="#1baf7a", lw=1.8)
    ax.semilogy(vp, rtg, color="#52514e", lw=1.2, ls="--")
    ax.text(0.45, 300, "NMOS (g=3.3)", color=C_TEXT, fontsize=9, weight="bold")
    ax.text(2.45, 300, "PMOS (g=0)", color=C_TEXT, fontsize=9, weight="bold")
    ax.text(1.45, 90, "t-gate", color=C_TEXT2, fontsize=8)
    for x, lab in ((0.4, "VREFN'"), (0.9, "VCM'"), (1.4, "VREFP'"),
                   (1.15, ""), (1.65, ""), (2.15, "old VREFP")):
        ax.axvline(x, color="#e5e4e0", lw=1.0)
        if lab:
            ax.text(x, 6e5, lab, color=C_TEXT2, fontsize=8, ha="center")
    ax.set_xlabel("passed voltage [V]", color=C_TEXT2, fontsize=9)
    ax.set_ylabel(f"ron [ohm], W={W} um, L=0.5 um", color=C_TEXT2, fontsize=9)
    ax.set_title("pass-switch on-resistance vs passed voltage",
                 color=C_TEXT, fontsize=10, loc="left")
    ax.set_ylim(50, 1e6)
    fig.tight_layout()
    return fig_to_b64(fig), vp, rn


def main():
    os.makedirs("spice", exist_ok=True)
    nf, pf, ron = run_deck("spice")

    vthn = vth_cc(nf[:, 0], np.abs(nf[:, 1]), LS[0])
    vthp = vth_cc(VDD - pf[:, 0], np.abs(pf[:, 1]), LS[0])  # sorted inside
    g_b64 = gmid_panels(nf, pf)
    r_b64, vp, rn = ron_panel(ron)

    probe = [0.4, 0.9, 1.4, 1.65, 2.15]
    rvals = {v: float(np.interp(v, vp, rn)) for v in probe}
    print(f"Vth(cc, L=0.5): nfet {vthn:.2f} V, pfet {vthp:.2f} V")
    for v in probe:
        print(f"  NMOS switch ron @ Vpass={v:.2f} V: {rvals[v]:8.0f} ohm  (W=10um)")

    rows = "\n".join(
        f"<tr><td>{v:.2f} V</td><td>{rvals[v]:,.0f} &Omega;</td>"
        f"<td>{rvals[v]*W/1000:,.0f} &Omega;&middot;um</td></tr>" for v in probe)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>sky130 3.3V FET characterization</title>
<style>
 body {{ background:{C_SURF}; color:{C_TEXT}; font-family:sans-serif;
        max-width:1000px; margin:2em auto; padding:0 1em; }}
 h1 {{ font-size:1.3em; }} h2 {{ font-size:1.05em; margin-top:1.6em; }}
 p {{ color:{C_TEXT2}; font-size:0.92em; line-height:1.5; }}
 table {{ border-collapse:collapse; margin:1em 0; }}
 th,td {{ border:1px solid #e5e4e0; padding:0.4em 0.9em; font-size:0.9em; }}
 th {{ color:{C_TEXT2}; font-weight:600; }}
 img {{ max-width:100%; }}
</style></head><body>
<h1>sky130 3.3&nbsp;V FET characterization (tt corner)</h1>
<p>Devices: sky130_fd_pr__nfet/pfet_g5v0d10v5, W = {W} um.
Constant-current Vth (Id = 1&mu;A&middot;W/L, L = 0.5): nfet {vthn:.2f} V,
pfet {vthp:.2f} V.</p>
<h2>gm/Id vs current density (OTA sizing curves)</h2>
<p>Weak inversion plateau left, strong inversion right. Pick a gm/Id, read
the current density, get W from the target current.</p>
<img src="data:image/png;base64,{g_b64}">
<h2>Pass-switch ron vs passed voltage (reference-window decision)</h2>
<p>NMOS with 3.3 V gate, PMOS with 0 V gate, both W = {W}/0.5 um; dashed =
parallel t-gate. Vertical markers: proposed low window
(0.4/0.9/1.4 V) and the old 3.3 V-centered VREFP at 2.15 V.</p>
<img src="data:image/png;base64,{r_b64}">
<table>
<tr><th>passed voltage</th><th>NMOS ron (W=10um)</th><th>ron&middot;W</th></tr>
{rows}
</table>
</body></html>
"""
    os.makedirs("reports", exist_ok=True)
    open("reports/fet_char.html", "w").write(html)
    print("wrote reports/fet_char.html")


if __name__ == "__main__":
    main()
