#!/usr/bin/env python3
"""DFF retimer, transistor level (tier 2, sky130 5V devices, 3.3 V).

Static CMOS master-slave DFF with transmission gates: master transparent
while CLK is low, latches on the rising edge; slave transparent while CLK
is high. The retimer's job in the loop (DESIGN.md): the comparator's SR
output wanders mid-half-period as the decision completes -- the DFF pins
the DAC drive to the clock edge so feedback pulse timing is bit-history
independent (ISI is the modulator's #1 ranked non-ideality).

Testbench: the REAL comparator (sim/comp_tb.py subckt) drives the DFF.
Input alternates sign every cycle with a small overdrive, clocked at
50 MHz. Checks, per cycle: Q/QB full rail; Q changes only inside a small
window after the rising clock edge (never mid-cycle, which is exactly the
comparator-output behavior being masked); clk-to-Q delay.

Usage: python3 sim/dff_tb.py    (sizes in DSIZES below)
Writes reports/results/dff.json.
"""

import json
import os
import subprocess
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.comp_tb import (SIZES as CSIZES, comp_subckt, WUNIT, NF, PF,
                         PDK_LIB, VDD, m)

DSIZES = dict(W_TG=5, W_INV=5, L=0.5)

NCYC = 12           # clock cycles simulated
TPER = 20e-9


def dff_subckt(p):
    def fet(name, model, d, g, s, b, w):
        return (f"{name} {d} {g} {s} {b} {model} W={WUNIT} L={p['L']} "
                f"nf=1 m={m(w)}")
    inv = lambda n, i, o: "\n".join([
        fet(f"XI{n}P", PF, o, i, "VDD", "VDD", p["W_INV"]),
        fet(f"XI{n}N", NF, o, i, "VSS", "VSS", p["W_INV"])])
    tg = lambda n, a, b_, cn, cp: "\n".join([
        fet(f"XT{n}N", NF, a, cn, b_, "VSS", p["W_TG"]),
        fet(f"XT{n}P", PF, a, cp, b_, "VDD", p["W_TG"])])
    return f"""
.subckt dff D CLK Q QB VDD VSS
{inv("C", "CLK", "clkb")}
* master: transparent CLK low (tg passes), latched at rising edge
{tg("M", "D", "mi", "clkb", "CLK")}
{inv("M1", "mi", "mb")}
{inv("M2", "mb", "mfb")}
{tg("MF", "mfb", "mi", "CLK", "clkb")}
* slave: transparent CLK high
{tg("S", "mb", "si", "CLK", "clkb")}
{inv("S1", "si", "QB")}
{inv("S2", "QB", "sfb")}
{tg("SF", "sfb", "si", "clkb", "CLK")}
{inv("Q1", "QB", "Q")}
.ends
"""


def deck():
    # comparator input: alternating-sign 20 mV overdrive, one flip per
    # cycle -- the hardest retiming pattern (Q must move every edge)
    pw = []
    for k in range(NCYC + 1):
        t0 = k * TPER
        v = 0.9 + (0.02 if k % 2 else -0.02)
        pw += [(t0 + 1e-12, v), ((k + 1) * TPER, v)]
    pwl = " ".join(f"{t:.11g} {v:.4f}" for t, v in pw)
    return f"""* comparator + DFF retimer chain (generated by sim/dff_tb.py)
.lib {PDK_LIB} tt
{comp_subckt(CSIZES)}
{dff_subckt(DSIZES)}
.options method=gear reltol=1e-4 vntol=1e-6 abstol=1e-12
VDDS vddi 0 {VDD}
RVDD vddi vdd 1
VCLK clkr 0 PULSE({VDD} 0 10n 0.2n 0.2n 9.8n {TPER * 1e9:.9g}n)
RCLK clkr clk 10
VP inpr 0 PWL({pwl})
RP inpr inp 10
VM inmr 0 0.9
RM inmr inm 10
XC inp inm clk cq cqb con1 con2 vdd 0 comp
XD cq clk q qb vdd 0 dff
.tran 0.01n {NCYC * TPER:.9g}
.control
run
wrdata dff_tb.csv v(cq) v(q) v(qb) v(clkr)
.endc
.end
"""


def main():
    os.makedirs("spice", exist_ok=True)
    open("spice/dff_tb.spice", "w").write(deck())
    r = subprocess.run(["ngspice", "-b", "dff_tb.spice"], cwd="spice",
                       capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-1500:])
        sys.exit(1)
    d = np.loadtxt("spice/dff_tb.csv")
    t, cq, q, qb = d[:, 0], d[:, 1], d[:, 3], d[:, 5]

    # rising clock edges (clk starts high; rises at k*TPER for k>=1)
    edges = [k * TPER for k in range(1, NCYC)]
    tq_max, viol, flips = 0.0, 0, 0
    for te in edges[1:-1]:
        # Q transitions must happen only within [te, te+3ns]
        win = (t > te + 3e-9) & (t < te + TPER - 0.1e-9)
        if win.any():
            dq = np.abs(np.diff(q[win]))
            if (dq > 0.5).any():
                viol += 1
        # clk-to-Q: Q settled state before vs after edge
        pre = q[(t > te - 1e-9) & (t < te - 0.1e-9)].mean()
        post = q[(t > te + 4e-9) & (t < te + 5e-9)].mean()
        if abs(post - pre) > 0.5 * VDD:
            flips += 1
            target = post
            cross = (t >= te) & (np.abs(q - target) < 0.1 * VDD)
            tq = t[cross][0] - te if cross.any() else float("nan")
            tq_max = max(tq_max, tq)
        # rails
        settle = (t > te + 5e-9) & (t < te + 9e-9)
        if not (q[settle].min() < 0.05 * VDD or
                q[settle].max() > 0.95 * VDD):
            viol += 1

    print(f"cycles checked: {len(edges) - 2}, Q flips seen: {flips} "
          f"(alternating input -> expect every cycle)")
    print(f"clk-to-Q (max): {tq_max*1e9:.2f} ns")
    print(f"mid-cycle Q transitions / rail failures: {viol} "
          f"(the comparator's cq wanders mid-cycle; q must not)")
    ok = viol == 0 and flips >= len(edges) - 4 and tq_max < 3e-9
    print("PASS" if ok else "FAIL")
    os.makedirs("reports/results", exist_ok=True)
    import shutil
    shutil.copy("spice/dff_tb.csv", "reports/results/dff_wave.csv")
    json.dump(dict(clk_to_q_ns=round(tq_max * 1e9, 2), flips=int(flips),
                   violations=int(viol), ok=bool(ok)),
              open("reports/results/dff.json", "w"), indent=1)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
