#!/usr/bin/env python3
"""OTA noise in the precision band (tier 2), closing DESIGN.md open
item 8: is 1/f noise eating the 10-12 ENOB precision-path budget?

Why a dedicated bench: every acceptance number in this repo comes from
.tran runs, and transient analysis simulates ZERO device noise -- no
flicker, no thermal -- so 1/f is invisible to the whole CI suite. This
bench runs ngspice .noise (linearized small-signal noise with the
sky130 BSIM4 flicker parameters) on the OTA reused from sim/ota_tb.py
(same SIZES / same extracted netlist with --pex).

Method: the integrator has no DC feedback path, so .noise runs on the
unity-buffer configuration where the operating point is exact and the
OTA's input-referred noise appears at the output with gain ~1. The
spectrum is then referred to the MODULATOR input analytically with the
params.py passives:

  noise gain   Gn = 1 + RIN/RDAC + RIN/ROFF     (OTA en at the sum node)
  resistors    4kT*RIN*Gn  V^2/Hz               (RIN + referred RDAC/ROFF)

total = sqrt( integral(en^2)*Gn^2 + 4kT*RIN*Gn*BW ) over 10 Hz-100 kHz
(the precision band; 10 Hz lower edge is conservative for 1/f).

Budget: precision-path quantization floor is 66 dB below the -4.4 dBFS
signal (0.99 V amp) = 350 uV rms at the input pin. ACCEPT: analog
input-referred noise <= 150 uV rms -- 6 dB+ under the quantization
floor (<= 1 dB SNDR cost) and inside a 12-ENOB (74 dB) aspiration.
Out of scope, noted: reference-buffer and comparator noise (comparator
noise is part of the measured decision-path floor, DESIGN.md
2026-07-20 night entry).

Usage: python3 sim/noise_tb.py [--pex]
Writes reports/results/noise{_pex}.json.
"""

import json
import os
import re
import subprocess
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import params as P
from sim.ota_tb import PDK_LIB, SIZES, deck

KT4 = 4 * 1.380649e-23 * 300.0
F_LO, F_HI = 10.0, P.FS / (2 * P.OSR_PREC)      # 10 Hz .. 100 kHz
GATE_UV = 150.0


def ota_subckt(pex):
    """The .subckt ota card exactly as ota_tb simulates it (in pex mode
    including the .include of the extracted layout netlist)."""
    d = deck(SIZES, pex=pex)
    start = d.index(".include" if pex else ".subckt ota")
    body = d[start:]
    return body[:body.index("\n.ends") + len("\n.ends")]


def noise_deck(pex):
    return f"""* OTA noise testbench (generated by sim/noise_tb.py)
.lib {PDK_LIB} tt
{"" if not pex else ""}{ota_subckt(pex)}
VDD vdd 0 3.3
VIN vin 0 DC {SIZES['VCM']} AC 1
XN vin outn outn vdd 0 ota
CLN outn 0 {SIZES['CL']}
.control
op
noise v(outn) VIN dec 20 10 10meg
setplot noise1
wrdata ota_noise.csv onoise_spectrum
.endc
.end
"""


def main():
    pex = "--pex" in sys.argv
    tag = "pex" if pex else "sch"
    os.makedirs("spice", exist_ok=True)
    open("spice/noise_tb.spice", "w").write(noise_deck(pex))
    r = subprocess.run(["ngspice", "-b", "noise_tb.spice"], cwd="spice",
                       capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-2000:])
        sys.exit(1)

    d = np.loadtxt("spice/ota_noise.csv")       # f, en [V/rtHz]
    f, en = d[:, 0], d[:, 1]
    white = np.median(en[(f > 1e6) & (f < 1e7)])
    # 1/f corner: last frequency where the spectrum exceeds sqrt(2)*white
    above = f[en > np.sqrt(2) * white]
    fc = float(above.max()) if above.size else 0.0

    band = (f >= F_LO) & (f <= F_HI)
    # numpy 2.x has only trapezoid, <2.0 only trapz; the default argument
    # of getattr is evaluated eagerly, so it cannot reference np.trapz
    trapezoid = getattr(np, "trapezoid", None) or np.trapz
    en2 = trapezoid(en[band] ** 2, f[band])     # OTA, at its own input [V^2]
    gn = 1 + P.RIN / P.RDAC + P.RIN / P.ROFF
    v_ota = np.sqrt(en2) * gn
    v_res = np.sqrt(KT4 * P.RIN * gn * (F_HI - F_LO))
    v_tot = np.sqrt(v_ota ** 2 + v_res ** 2)

    quant_uv = np.sqrt(P.AMP ** 2 / 2 / 10 ** 6.6) * 1e6   # 66 dB floor
    ok = v_tot * 1e6 <= GATE_UV
    print(f"OTA noise ({tag}), band {F_LO:.0f} Hz - {F_HI/1e3:.0f} kHz, "
          f"noise gain Gn={gn:.2f}")
    print(f"  OTA en: white {white*1e9:.1f} nV/rtHz, 1/f corner "
          f"{fc/1e3:.1f} kHz, band rms {np.sqrt(en2)*1e6:.1f} uV")
    print(f"  input-referred: OTA {v_ota*1e6:.0f} uV + resistors "
          f"{v_res*1e6:.0f} uV = {v_tot*1e6:.0f} uV rms")
    print(f"  budget: quantization floor {quant_uv:.0f} uV, gate "
          f"<= {GATE_UV:.0f} uV")
    os.makedirs("reports/results", exist_ok=True)
    json.dump(dict(white_nv=round(float(white) * 1e9, 2),
                   fc_1f_hz=round(fc),
                   en_band_uv=round(float(np.sqrt(en2)) * 1e6, 1),
                   gn=round(float(gn), 2),
                   in_ref_ota_uv=round(float(v_ota) * 1e6, 1),
                   in_ref_res_uv=round(float(v_res) * 1e6, 1),
                   in_ref_total_uv=round(float(v_tot) * 1e6, 1),
                   quant_floor_uv=round(float(quant_uv)),
                   gate_uv=GATE_UV, ok=bool(ok)),
              open(f"reports/results/noise_{tag}.json", "w"), indent=1)
    print("ACCEPT" if ok else "REJECT -- noise above the precision budget")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
