#!/usr/bin/env python3
"""Equivalence check: xschem-generated OTA subckt vs sim/ota_tb.py results.

Extracts .subckt ota from spice/ota_top.spice (xschem netlist of the
generated schematic), wraps it in the same AC open-loop testbench, and
compares A0/GBW/PM against the inline-testbench values. Run after
`python3 tools/gen_ota_sch.py` + xschem netlisting (or `make xcheck`).
"""

import os
import re
import subprocess
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.ota_tb import SIZES as S, PDK_LIB

sub = re.search(r"^\.subckt ota .*?^\.ends\b", open("spice/ota_top.spice").read(),
                re.M | re.S)
if not sub:
    sys.exit("no .subckt ota in spice/ota_top.spice -- netlist ota_top.sch first")

deck = f"""* xschem OTA equivalence check (generated by sim/ota_xcheck.py)
.lib {PDK_LIB} tt
{sub.group(0)}

VDDA vdda 0 3.3
VCMA vcma 0 {S['VCM']}
VINA ina vcma DC 0 AC 1
LFB outa inma 1e6
CFB inma vcma 1e6
CLA outa 0 {S['CL']}
IRPA irefpa 0 {S['IREFP']}
IRNA vdda irefna {S['IREFN']}
VBNCA vbnca 0 {S['VBNC']}
VBPCA vbpca 0 {S['VBPC']}
XA ina inma outa vdda 0 irefpa irefna vbnca vbpca ota
.control
op
ac dec 20 100 3g
wrdata xchk_ac.csv v(outa)
.endc
.end
"""
open("spice/ota_xcheck.spice", "w").write(deck)
r = subprocess.run(["ngspice", "-b", "ota_xcheck.spice"], cwd="spice",
                   capture_output=True, text=True)
if r.returncode:
    print(r.stderr[-1500:])
    sys.exit(1)

ac = np.loadtxt("spice/xchk_ac.csv")
f, h = ac[:, 0], ac[:, 1] + 1j * ac[:, 2]
mag, ph = np.abs(h), np.unwrap(np.angle(h)) * 180 / np.pi
a0 = 20 * np.log10(mag[0])
i = np.argmax(mag < 1)
ugf = 10 ** np.interp(0, [np.log10(mag[i]), np.log10(mag[i - 1])],
                      [np.log10(f[i]), np.log10(f[i - 1])])
pm = 180 + np.interp(np.log10(ugf), np.log10(f), ph)
print(f"xschem-netlist OTA:  A0={a0:.1f} dB  GBW={ugf/1e6:.0f} MHz  PM={pm:.0f} deg")
print("inline reference  :  A0=65.2 dB  GBW=209 MHz  PM=58 deg  (tt)")
ok = abs(a0 - 65.2) < 1 and abs(ugf / 1e6 - 209) < 10 and abs(pm - 58) < 3
print("MATCH" if ok else "MISMATCH -- investigate")
sys.exit(0 if ok else 1)
