#!/usr/bin/env python3
"""Folded-cascode OTA sizing testbench (tier 2, sky130 3.3V devices).

Topology: PMOS input pair (input CM = 0.9 V per DESIGN.md item 6), NMOS
folded branch with cascodes, cascoded PMOS mirror load (single-ended out),
tail and sink currents set by 1:1 mirrors from ideal references; cascode
gate biases ideal for now (bias generator is a later block).

Three DUT copies in one deck (one sky130 lib parse):
  - AC open loop (L/C feedback trick) -> A0, GBW, phase margin; VDD current
  - unity buffer + 1 V step         -> slew rate up/down, settling
  - unity buffer DC sweep           -> usable in/out range

Targets (DESIGN.md block requirements): A0 >= 1000 (60 dB),
GBW 150-200 MHz into 1.5 pF, SR >= 200 V/us, PM >= 60 deg.

Usage: python3 sim/ota_tb.py    (sizes in the SIZES dict below)
"""

import os
import subprocess
import sys

import numpy as np

PDK_ROOT = os.environ.get("PDK_ROOT", "/home/nvme/pdk")
PDK_LIB = f"{PDK_ROOT}/sky130A/libs.tech/ngspice/sky130.lib.spice"

# W_* are TOTAL widths in um; devices are emitted as m= parallel copies of
# WUNIT-wide fingers (sky130 5V fets are width-binned: arbitrary single-device
# W is rejected by the model binning)
WUNIT = 5

SIZES = dict(
    W_IN=250, L_IN=0.7,     # input pair, 190 uA each
    W_TAIL=380, L_TAIL=1.0, # tail + its diode, 380 uA
    W_SINK=120, L_SINK=1.2, # folded-branch NMOS sinks, 315 uA each
    W_CAS=120, L_CAS=1.0,   # NMOS cascodes, low density for Vov+ro
    W_MIR=60, L_MIR=0.7,    # PMOS mirror (small: mirror-pole PM)
    W_PCAS=60, L_PCAS=0.7,  # PMOS cascodes
    VBNC=1.5, VBPC=0.5,     # cascode gate biases (ideal, v1)
    IREFP=380e-6, IREFN=340e-6,
    CL=1.5e-12, VCM=0.9,
)


def deck(p, pex=False):
    nf = "sky130_fd_pr__nfet_g5v0d10v5"
    pf = "sky130_fd_pr__pfet_g5v0d10v5"
    if pex:
        # extracted layout (tools/pex_ota.py) wrapped to the same 5-pin
        # interface: layout exposes the bias nets, supply them here exactly
        # as the schematic subckt does internally
        ota = f"""
.include ota_pex.spice
.subckt ota INP INM OUT VDD VSS
XCORE IREFP VDD INP INM VBPC VBNC VSS IREFN OUT ota_layout
IRP IREFP VSS {p['IREFP']}
IRN VDD IREFN {p['IREFN']}
VBNC vbnc VSS {p['VBNC']}
VBPC vbpc VSS {p['VBPC']}
.ends
"""
        return header(p, ota)
    ota = f"""
.subckt ota INP INM OUT VDD VSS
* bias mirrors from ideal references
XDP vbt vbt VDD VDD {pf} W={WUNIT} L={p['L_TAIL']} nf=1 m={max(1, round(p['W_TAIL'] / WUNIT))}
IRP vbt VSS {p['IREFP']}
XDN vbn vbn VSS VSS {nf} W={WUNIT} L={p['L_SINK']} nf=1 m={max(1, round(p['W_SINK'] / WUNIT))}
IRN VDD vbn {p['IREFN']}
VBNC vbnc VSS {p['VBNC']}
VBPC vbpc VSS {p['VBPC']}
* core
XT tail vbt VDD VDD {pf} W={WUNIT} L={p['L_TAIL']} nf=1 m={max(1, round(p['W_TAIL'] / WUNIT))}
X1 fn1 INP tail tail {pf} W={WUNIT} L={p['L_IN']} nf=1 m={max(1, round(p['W_IN'] / WUNIT))}
X2 fn2 INM tail tail {pf} W={WUNIT} L={p['L_IN']} nf=1 m={max(1, round(p['W_IN'] / WUNIT))}
X3 fn1 vbn VSS VSS {nf} W={WUNIT} L={p['L_SINK']} nf=1 m={max(1, round(p['W_SINK'] / WUNIT))}
X4 fn2 vbn VSS VSS {nf} W={WUNIT} L={p['L_SINK']} nf=1 m={max(1, round(p['W_SINK'] / WUNIT))}
X5 dio vbnc fn1 VSS {nf} W={WUNIT} L={p['L_CAS']} nf=1 m={max(1, round(p['W_CAS'] / WUNIT))}
X6 OUT vbnc fn2 VSS {nf} W={WUNIT} L={p['L_CAS']} nf=1 m={max(1, round(p['W_CAS'] / WUNIT))}
X9 pc1 dio VDD VDD {pf} W={WUNIT} L={p['L_MIR']} nf=1 m={max(1, round(p['W_MIR'] / WUNIT))}
X10 pc2 dio VDD VDD {pf} W={WUNIT} L={p['L_MIR']} nf=1 m={max(1, round(p['W_MIR'] / WUNIT))}
X7 dio vbpc pc1 VDD {pf} W={WUNIT} L={p['L_PCAS']} nf=1 m={max(1, round(p['W_PCAS'] / WUNIT))}
X8 OUT vbpc pc2 VDD {pf} W={WUNIT} L={p['L_PCAS']} nf=1 m={max(1, round(p['W_PCAS'] / WUNIT))}
.ends
"""
    return header(p, ota)


def header(p, ota):
    return f"""* folded-cascode OTA testbench (generated by sim/ota_tb.py)
.lib {PDK_LIB} tt
{ota}
* --- DUT A: AC open loop ---
VDDA vdda 0 3.3
VCMA vcma 0 {p['VCM']}
VINA ina vcma DC 0 AC 1
LFB outa inma 1e6
CFB inma vcma 1e6
CLA outa 0 {p['CL']}
XA ina inma outa vdda 0 ota

* --- DUT B: unity buffer, step for slew ---
VDDB vddb 0 3.3
VSTEP inb 0 PULSE(0.4 1.4 0.1u 1n 1n 0.4u 1u)
CLB outb 0 {p['CL']}
XB inb outb outb vddb 0 ota

* --- DUT C: unity buffer, DC sweep for range ---
VDDC vddc 0 3.3
VSW inc 0 0
CLC outc 0 {p['CL']}
XC inc outc outc vddc 0 ota

.control
op
wrdata ota_op.csv v(outa) i(VDDA)
ac dec 20 100 3g
wrdata ota_ac.csv v(outa)
tran 0.2n 1u
wrdata ota_tr.csv v(outb) v(inb)
dc VSW 0 3.3 0.01
wrdata ota_dc.csv v(outc)
.endc
.end
"""


def run(p, pex=False):
    os.makedirs("spice", exist_ok=True)
    if pex:
        print("=== PEX mode: extracted layout netlist (spice/ota_pex.spice) "
              "===")
    open("spice/ota_tb.spice", "w").write(deck(p, pex=pex))
    r = subprocess.run(["ngspice", "-b", "ota_tb.spice"], cwd="spice",
                       capture_output=True, text=True)
    if r.returncode:
        print(r.stderr[-2000:])
        sys.exit(1)

    op = np.loadtxt("spice/ota_op.csv")
    vout0, idd = op[1], abs(op[3])

    ac = np.loadtxt("spice/ota_ac.csv")     # f re im
    f, h = ac[:, 0], ac[:, 1] + 1j * ac[:, 2]
    mag, ph = np.abs(h), np.unwrap(np.angle(h)) * 180 / np.pi
    a0_db = 20 * np.log10(mag[0])
    if (mag < 1).any() and mag[0] > 1:
        i = np.argmax(mag < 1)
        ugf = np.interp(0, [np.log10(mag[i]), np.log10(mag[i - 1])],
                        [np.log10(f[i]), np.log10(f[i - 1])])
        ugf = 10 ** ugf
        pm = 180 + np.interp(np.log10(ugf), np.log10(f), ph)
    else:
        ugf, pm = float("nan"), float("nan")

    tr = np.loadtxt("spice/ota_tr.csv")
    t, vo = tr[:, 0], tr[:, 1]
    dv = np.gradient(vo, t)
    rise = (t > 0.09e-6) & (t < 0.3e-6)
    fall = (t > 0.49e-6) & (t < 0.8e-6)
    sr_up, sr_dn = dv[rise].max(), abs(dv[fall].min())

    dc = np.loadtxt("spice/ota_dc.csv")
    vin, vout = dc[:, 0], dc[:, 1]
    ok = np.abs(vout - vin) < 0.01
    lo = vin[ok].min() if ok.any() else float("nan")
    hi = vin[ok].max() if ok.any() else float("nan")

    print(f"op:    out={vout0:.3f} V (CM {p['VCM']}), Ivdd={idd*1e6:.0f} uA "
          f"({idd*3.3*1e3:.2f} mW)")
    print(f"AC:    A0={a0_db:.1f} dB, GBW={ugf/1e6:.0f} MHz, PM={pm:.0f} deg")
    print(f"slew:  +{sr_up/1e6:.0f} / -{sr_dn/1e6:.0f} V/us")
    print(f"range: buffer tracks {lo:.2f} .. {hi:.2f} V")
    print(f"targets: A0>=60 dB, GBW 150-200 MHz, PM>=60, SR>=200 V/us, "
          f"range covers 0.4..1.4 V")


if __name__ == "__main__":
    run(SIZES, pex="--pex" in sys.argv)
