#!/usr/bin/env python3
"""Emit the golden .subckt netlists for the support blocks.

Single source of truth stays the SIZES dicts in each sim/<b>_tb.py; this
tool just writes the subckt text those TBs simulate into
spice/golden/<b>.spice, where the schematic equivalence check
(tools/xcheck_blocks.py) and block LVS consume it.

bias is emitted with layout=True (real poly-R / MiM device cards, the
ngspice-model-calibrated geometries) -- that variant is ACCEPT-verified
by `python3 sim/bias_tb.py --layout`.

Usage: python3 tools/gen_golden.py   (from repo root)
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.comp_tb import SIZES as CSIZES, comp_subckt
from sim.dff_tb import DSIZES, dff_subckt
from sim.bias_tb import BSIZES, bias_subckt
from sim.buf_tb import FSIZES, buf_subckt
from sim.lvl_tb import LSIZES, lvl_subckt
from sim.odrv_tb import OSIZES, odrv_subckt

BLOCKS = {
    "comp": lambda: comp_subckt(CSIZES),
    "dff": lambda: dff_subckt(DSIZES),
    "bias": lambda: bias_subckt(BSIZES, layout=True),
    "buf": lambda: buf_subckt(FSIZES),
    "lvl": lambda: lvl_subckt(LSIZES),
    "odrv": lambda: odrv_subckt(OSIZES),
}


def main():
    os.makedirs("spice/golden", exist_ok=True)
    for name, fn in BLOCKS.items():
        path = f"spice/golden/{name}.spice"
        txt = (f"* GOLDEN {name} netlist -- GENERATED by tools/gen_golden.py"
               f" from sim/{name}_tb.py sizes; do not edit\n" + fn().strip()
               + "\n")
        open(path, "w").write(txt)
        ndev = sum(1 for ln in txt.splitlines()
                   if ln[:1] in "XR" and not ln.startswith("*"))
        print(f"wrote {path} ({ndev} devices)")


if __name__ == "__main__":
    main()
