#!/usr/bin/env python3
"""Emit the top-level golden netlist: spice/golden/top.spice.

.subckt sd_top UA0 UA1 UO0 UO1 CLK VDPWR VAPWR VGND -- the full
modulator stitched from the block goldens (inlined) plus the passive
cells, whose device cards are lifted from their magic extractions
(mag/<cell>.spice) so golden and layout agree on drawn geometry.

Connectivity contract (tier-1 truth, STATUS step 4):
  UA0 -RIN- sum; OTA(INP=vcm, INM=sum, OUT=int); CINT int<->sum;
  comp(INP=int, INM=vcm, CLK=clk33) -> cq -> DFF(clk33) -> q33/qb33;
  DAC: S_MID dac<->vcm gated clk33 (return phase, clk high);
       S_TOP vrefp-xt-dac gated q33 & clkb33 (series pair);
       S_BOT vrefn-xb-dac gated qb33 & clkb33; RDAC dac-sum;
  ladder VAPWR -190k- lad_p -50k- lad_c -50k- lad_n -40k- VGND;
  buf x3: lad_* -> vrefp/vcm/vrefn (tail off the OTA IREFP line);
  cdec x3 on the refs, cflt x2 on vbnc/vbpc; lvl CLK->clk33/clkb33;
  odrv x2 q33/qb33 -> UO0/UO1; UA1 = int monitor.

Usage: python3 tools/gen_top_golden.py   (after gen_golden + layout
cells exist)
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

BLOCKS = ["ota", "comp", "dff", "bias", "buf", "lvl", "odrv"]

# passive instances: (instname, cell, portmap)
PASSIVES = [
    ("RIN", "rin", {"R1": "UA0", "R2": "sum", "B": "VGND"}),
    ("RDAC", "rdac", {"R1": "dac", "R2": "sum", "B": "VGND"}),
    ("RLT", "rl_top", {"R1": "VAPWR", "R2": "lad_p", "B": "VGND"}),
    ("RLP", "rl_pc", {"R1": "lad_p", "R2": "lad_c", "B": "VGND"}),
    ("RLC", "rl_cm", {"R1": "lad_c", "R2": "lad_n", "B": "VGND"}),
    ("RLB", "rl_bot", {"R1": "lad_n", "R2": "VGND", "B": "VGND"}),
    ("CINT", "cint", {"C1": "UA1", "C2": "sum"}),
    ("CDP", "cdec", {"C1": "vrefp", "C2": "VGND"}),
    ("CDC", "cdec", {"C1": "vcm", "C2": "VGND"}),
    ("CDN", "cdec", {"C1": "vrefn", "C2": "VGND"}),
    ("CBN", "cflt", {"C1": "vbnc", "C2": "VGND"}),
    ("CBP", "cflt", {"C1": "vbpc", "C2": "VGND"}),
    ("SM", "sw_nmos", {"D": "dac", "G": "clk33", "S": "vcm",
                       "B": "VGND"}),
    ("ST1", "sw_nmos", {"D": "vrefp", "G": "q33", "S": "xt",
                        "B": "VGND"}),
    ("ST2", "sw_nmos", {"D": "xt", "G": "clkb33", "S": "dac",
                        "B": "VGND"}),
    ("SB1", "sw_nmos", {"D": "vrefn", "G": "qb33", "S": "xb",
                        "B": "VGND"}),
    ("SB2", "sw_nmos", {"D": "xb", "G": "clkb33", "S": "dac",
                        "B": "VGND"}),
]

INSTANCES = [
    "XOTA vcm sum UA1 VAPWR VGND irefp irefn vbnc vbpc ota",
    "XCOMP UA1 vcm clk33 cq cqb con1 con2 VAPWR VGND comp",
    "XDFF cq clk33 q33 qb33 VAPWR VGND dff",
    "XBIAS irefp irefn vbnc vbpc VAPWR VGND bias",
    "XBUFP lad_p vrefp irefp VAPWR VGND buf",
    "XBUFC lad_c vcm irefp VAPWR VGND buf",
    "XBUFN lad_n vrefn irefp VAPWR VGND buf",
    "XLVL CLK clk33 clkb33 VDPWR VAPWR VGND lvl",
    "XODRVQ q33 UO0 VDPWR VGND odrv",
    "XODRVB qb33 UO1 VDPWR VGND odrv",
]


def passive_cards(inst, cell, portmap):
    """Lift the unit device cards from mag/<cell>.spice with mapped
    nodes (all C1_*/C2_* style ports map to their base name)."""
    txt = open(f"mag/{cell}.spice").read()
    sub = re.search(r"^\.subckt (\S+) (.*?)\n(.*?)^\.ends", txt,
                    re.M | re.S)
    cards = []
    k = 0
    for ln in sub.group(3).splitlines():
        t = ln.split()
        if not t or not t[0].startswith("X"):
            continue
        mi = next(i for i, tok in enumerate(t) if "sky130_fd_pr__" in tok)
        nodes = []
        for n in t[1:mi]:
            base = re.sub(r"_\d+$", "", n)
            if base in portmap:
                nodes.append(portmap[base])
            else:
                nodes.append(f"{inst.lower()}_{n.lower()}")
        cards.append(f"X{inst}{k if k else ''} " + " ".join(nodes)
                     + " " + " ".join(t[mi:]))
        k += 1
    return cards


def main():
    out = ["* GOLDEN top netlist -- GENERATED by tools/gen_top_golden.py"]
    for b in BLOCKS:
        if b == "ota":
            txt = open("spice/ota_top.spice").read()
            out.append(re.search(r"^\.subckt ota .*?^\.ends\b", txt,
                                 re.M | re.S).group(0))
        else:
            txt = open(f"spice/golden/{b}.spice").read()
            out.append(re.search(rf"^\.subckt {b}\b.*?^\.ends", txt,
                                 re.M | re.S).group(0))
    out.append(".subckt sd_top UA0 UA1 UO0 UO1 CLK VDPWR VAPWR VGND")
    out += INSTANCES
    # UA1 IS the integrator node (monitor pin = int, no series R)
    for inst, cell, pm in PASSIVES:
        out += passive_cards(inst, cell, pm)
    out.append(".ends")
    os.makedirs("spice/golden", exist_ok=True)
    open("spice/golden/top.spice", "w").write("\n".join(out) + "\n")
    ncards = len(INSTANCES) + sum(len(passive_cards(i, c, p))
                                  for i, c, p in PASSIVES)
    print(f"wrote spice/golden/top.spice ({ncards} top-level cards)")


if __name__ == "__main__":
    main()
