#!/usr/bin/env python3
"""Generate xschem/ota.sch from the frozen sizes in sim/ota_tb.py.

The schematic is the LVS golden reference; sizes have exactly one home
(sim.ota_tb.SIZES), so regenerate after any resize:  python3 tools/gen_ota_sch.py
Cell pins: INP INM OUT VDD VSS IREFP IREFN VBNC VBPC (bias currents and
cascode gate voltages come from the future bias block).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.ota_tb import SIZES as S, WUNIT

NF, PF = "nfet_g5v0d10v5", "pfet_g5v0d10v5"


def mult(wkey):
    return max(1, round(S[wkey] / WUNIT))


# name, x, y, model, D, G, S, B, L, mult
DEVICES = [
    ("MDP", -900, -800, PF, "IREFP", "IREFP", "VDD",  "VDD",  S["L_TAIL"], mult("W_TAIL")),
    ("MT",  -650, -800, PF, "tail",  "IREFP", "VDD",  "VDD",  S["L_TAIL"], mult("W_TAIL")),
    ("M1",  -650, -650, PF, "fn1",   "INP",   "tail", "tail", S["L_IN"],   mult("W_IN")),
    ("M2",  -450, -650, PF, "fn2",   "INM",   "tail", "tail", S["L_IN"],   mult("W_IN")),
    ("M9",  -300, -600, PF, "pc1",   "dio",   "VDD",  "VDD",  S["L_MIR"],  mult("W_MIR")),
    ("M10",    0, -600, PF, "pc2",   "dio",   "VDD",  "VDD",  S["L_MIR"],  mult("W_MIR")),
    ("M7",  -300, -450, PF, "dio",   "VBPC",  "pc1",  "VDD",  S["L_PCAS"], mult("W_PCAS")),
    ("M8",     0, -450, PF, "OUT",   "VBPC",  "pc2",  "VDD",  S["L_PCAS"], mult("W_PCAS")),
    ("M5",  -300, -300, NF, "dio",   "VBNC",  "fn1",  "VSS",  S["L_CAS"],  mult("W_CAS")),
    ("M6",     0, -300, NF, "OUT",   "VBNC",  "fn2",  "VSS",  S["L_CAS"],  mult("W_CAS")),
    ("M3",  -300, -150, NF, "fn1",   "IREFN", "VSS",  "VSS",  S["L_SINK"], mult("W_SINK")),
    ("M4",     0, -150, NF, "fn2",   "IREFN", "VSS",  "VSS",  S["L_SINK"], mult("W_SINK")),
    ("MDN", -900, -150, NF, "IREFN", "IREFN", "VSS",  "VSS",  S["L_SINK"], mult("W_SINK")),
]

PINS = [  # (symbol, label) -- file order defines nothing; ota.sym fixes port order
    ("ipin", "INP"), ("ipin", "INM"), ("opin", "OUT"),
    ("iopin", "VDD"), ("iopin", "VSS"),
    ("ipin", "IREFP"), ("ipin", "IREFN"), ("ipin", "VBNC"), ("ipin", "VBPC"),
]


def main():
    out = ["v {xschem version=3.4.4 file_version=1.2}",
           "G {}", "K {}", "V {}", "S {}", "E {}"]
    out.append("T {folded-cascode OTA - GENERATED by tools/gen_ota_sch.py "
               "from sim/ota_tb.py SIZES - do not edit by hand} -1500 -1000 0 0 0.4 0.4 {}")
    out.append("T {PMOS mirror / cascodes (top), NMOS cascodes / sinks (bottom); "
               "left column = bias diodes; unit finger W=%g} -1500 -960 0 0 0.3 0.3 {}" % WUNIT)
    for i, (sym, lab) in enumerate(PINS):
        x = -1500 + i * 120
        out.append(f"C {{devices/{sym}.sym}} {x} -900 0 0 {{name=pp{i} lab={lab}}}")
    n = 0
    for name, x, y, model, d, g, s, b, l, m in DEVICES:
        out.append(f"C {{sky130_fd_pr/{model}.sym}} {x} {y} 0 0 "
                   f"{{name={name} model={model} spiceprefix=X "
                   f"W={WUNIT} L={l:g} nf=1 mult={m} "
                   f"ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}}")
        # nfet symbol: D top / S bottom; pfet symbol: S top / D bottom
        dy_d, dy_s = (-30, 30) if model == NF else (30, -30)
        for lab, px, py, rot in ((d, x + 20, y + dy_d, 1), (g, x - 20, y, 0),
                                 (s, x + 20, y + dy_s, 3), (b, x + 45, y, 2)):
            out.append(f"C {{devices/lab_pin.sym}} {px} {py} {rot} 0 "
                       f"{{name=l{n} lab={lab}}}")
            n += 1
        # short stub from B pin (at x+20) to its label at x+45
        out.append(f"N {x + 20} {y} {x + 45} {y} {{lab={b}}}")
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "xschem", "ota.sch")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(DEVICES)} devices")


if __name__ == "__main__":
    main()
