#!/usr/bin/env python3
"""Generate xschem/comp.sch (+ comp.sym, comp_top.sch) from sim/comp_tb.py.

Same rule as the OTA: sizes have exactly one home (sim.comp_tb.SIZES) and
the schematic is generated from them, then proven equivalent by
sim/comp_xcheck.py (make compcheck). Pin order in comp.sym is the contract
the equivalence check and future LVS rely on:
  INP INM CLK Q QB ON1 ON2 VDD VSS
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sim.comp_tb import SIZES as S, WUNIT

NF, PF = "nfet_g5v0d10v5", "pfet_g5v0d10v5"


def mult(wkey):
    return max(1, round(S[wkey] / WUNIT))


# name, x, y, model, D, G, S, B, mult  (L is common: S["L"])
DEVICES = [
    # core StrongARM (left block): tail on top, input pair, cross pairs,
    # resets at the bottom
    ("XT",   -1100, -800, PF, "tail", "CLK", "VDD",  "VDD",  mult("W_TAIL")),
    ("X1",   -1250, -650, PF, "di1",  "INP", "tail", "VDD",  mult("W_IN")),
    ("X2",   -950,  -650, PF, "di2",  "INM", "tail", "VDD",  mult("W_IN")),
    ("X3",   -1250, -500, PF, "ON1",  "ON2", "di1",  "VDD",  mult("W_XP")),
    ("X4",   -950,  -500, PF, "ON2",  "ON1", "di2",  "VDD",  mult("W_XP")),
    ("X5",   -1250, -350, NF, "ON1",  "ON2", "VSS",  "VSS",  mult("W_XN")),
    ("X6",   -950,  -350, NF, "ON2",  "ON1", "VSS",  "VSS",  mult("W_XN")),
    ("XR1",  -1250, -200, NF, "di1",  "CLK", "VSS",  "VSS",  mult("W_RST")),
    ("XR2",  -1100, -200, NF, "di2",  "CLK", "VSS",  "VSS",  mult("W_RST")),
    ("XR3",  -950,  -200, NF, "ON1",  "CLK", "VSS",  "VSS",  mult("W_RST")),
    ("XR4",  -800,  -200, NF, "ON2",  "CLK", "VSS",  "VSS",  mult("W_RST")),
    # output chain (right block): inverter buffers (state-independent
    # loading on the regen nodes) + cross-coupled NAND2 SR latch
    ("XI1P", -650, -800, PF, "n1b", "ON1", "VDD", "VDD", mult("W_LG")),
    ("XI1N", -650, -650, NF, "n1b", "ON1", "VSS", "VSS", mult("W_LG")),
    ("XI2P", -650, -500, PF, "n2b", "ON2", "VDD", "VDD", mult("W_LG")),
    ("XI2N", -650, -350, NF, "n2b", "ON2", "VSS", "VSS", mult("W_LG")),
    ("XAQ1", -450, -800, PF, "Q",   "n2b", "VDD", "VDD", mult("W_LG")),
    ("XAQ2", -450, -650, PF, "Q",   "QB",  "VDD", "VDD", mult("W_LG")),
    ("XAQ3", -450, -500, NF, "Q",   "n2b", "sq",  "VSS", mult("W_LG")),
    ("XAQ4", -450, -350, NF, "sq",  "QB",  "VSS", "VSS", mult("W_LG")),
    ("XAB1", -150, -800, PF, "QB",  "n1b", "VDD", "VDD", mult("W_LG")),
    ("XAB2", -150, -650, PF, "QB",  "Q",   "VDD", "VDD", mult("W_LG")),
    ("XAB3", -150, -500, NF, "QB",  "n1b", "sb",  "VSS", mult("W_LG")),
    ("XAB4", -150, -350, NF, "sb",  "Q",   "VSS", "VSS", mult("W_LG")),
]

PINS = [("ipin", "INP"), ("ipin", "INM"), ("ipin", "CLK"),
        ("opin", "Q"), ("opin", "QB"), ("opin", "ON1"), ("opin", "ON2"),
        ("iopin", "VDD"), ("iopin", "VSS")]

# drawn wires (vertical branch runs + tail) so the core reads as a
# StrongARM; connectivity authority stays with the lab_pins
WIRES = [
    # clocked tail into the input pair's common source
    (-1080, -770, -1080, -700, "tail"),
    (-1230, -680, -1230, -700, "tail"), (-950 + 20, -680, -930, -700, "tail"),
    (-1230, -700, -930, -700, "tail"),
    # di columns: input pair drain down into the cross-PMOS source
    (-1230, -620, -1230, -530, "di1"), (-930, -620, -930, -530, "di2"),
    # regeneration columns: cross-PMOS drain onto cross-NMOS drain
    (-1230, -470, -1230, -380, "ON1"), (-930, -470, -930, -380, "ON2"),
    # output chain: inverter drains, NAND stack nodes
    (-630, -770, -630, -680, "n1b"), (-630, -470, -630, -380, "n2b"),
    (-430, -470, -430, -380, "sq"), (-130, -470, -130, -380, "sb"),
]


def write_sch(path):
    out = ["v {xschem version=3.4.4 file_version=1.2}",
           "G {}", "K {}", "V {}", "S {}", "E {}"]
    out.append("T {StrongARM comparator - GENERATED by tools/gen_comp_sch.py "
               "from sim/comp_tb.py SIZES - do not edit by hand} "
               "-1400 -1000 0 0 0.4 0.4 {}")
    out.append("T {PMOS input (senses the low window - DESIGN.md open item "
               "6), evaluates CLK low, precharge to VSS, NOR SR latch; "
               "unit finger W=%g L=%g} -1400 -960 0 0 0.3 0.3 {}"
               % (WUNIT, S["L"]))
    for i, (sym, lab) in enumerate(PINS):
        x = -1400 + i * 120
        out.append(f"C {{devices/{sym}.sym}} {x} -900 0 0 "
                   f"{{name=pp{i} lab={lab}}}")
    n = 0
    for name, x, y, model, d, g, s, b, m in DEVICES:
        out.append(f"C {{sky130_fd_pr/{model}.sym}} {x} {y} 0 0 "
                   f"{{name={name} model={model} spiceprefix=X "
                   f"W={WUNIT} L={S['L']:g} nf=1 mult={m} "
                   f"ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}}")
        # nfet symbol: D top / S bottom; pfet symbol: S top / D bottom
        dy_d, dy_s = (-30, 30) if model == NF else (30, -30)
        for lab, px, py, rot in ((d, x + 20, y + dy_d, 1), (g, x - 20, y, 0),
                                 (s, x + 20, y + dy_s, 3), (b, x + 45, y, 2)):
            out.append(f"C {{devices/lab_pin.sym}} {px} {py} {rot} 0 "
                       f"{{name=l{n} lab={lab}}}")
            n += 1
        out.append(f"N {x + 20} {y} {x + 45} {y} {{lab={b}}}")
    for x1, y1, x2, y2, lab in WIRES:
        out.append(f"N {x1} {y1} {x2} {y2} {{lab={lab}}}")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote {path}: {len(DEVICES)} devices")


def write_sym(path):
    out = ["v {xschem version=3.4.4 file_version=1.2}",
           "G {}",
           'K {type=subcircuit\nformat="@name @pinlist @symname"\n'
           'template="name=XCOMP"\n}',
           "V {}", "S {}", "E {}",
           "L 4 -100 -80 100 -80 {}", "L 4 100 -80 100 80 {}",
           "L 4 100 80 -100 80 {}", "L 4 -100 80 -100 -80 {}"]
    # pin order here IS the subckt port order: keep in sync with comp_tb
    pins = [("INP", "in", -140, -40), ("INM", "in", -140, 0),
            ("CLK", "in", -140, 40), ("Q", "out", 140, -40),
            ("QB", "out", 140, 0), ("ON1", "out", 140, 40),
            ("ON2", "out", 140, 60), ("VDD", "inout", -20, -100),
            ("VSS", "inout", -20, 100)]
    for name, d, x, y in pins:
        if abs(x) == 140:
            xs = -100 if x < 0 else 100
            out.append(f"L 4 {min(x, xs)} {y} {max(x, xs)} {y} {{}}")
        else:
            out.append(f"L 4 {x} {y} {x} {y - 20 if y > 0 else y + 20} {{}}")
        out.append(f"B 5 {x - 2.5} {y - 2.5} {x + 2.5} {y + 2.5} "
                   f"{{name={name} dir={d}}}")
    out += ["T {COMP} -35 -10 0 0 0.4 0.4 {}",
            "T {@name} -30 -120 0 0 0.25 0.25 {}",
            "T {+} -95 -48 0 0 0.3 0.3 {}",
            "T {-} -95 -8 0 0 0.3 0.3 {}",
            "T {clk} -95 32 0 0 0.25 0.25 {}"]
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote {path}")


def write_top(path):
    out = ["v {xschem version=3.4.4 file_version=1.2}",
           "G {}", "K {}", "V {}", "S {}", "E {}",
           "T {comp_top: netlisting wrapper - produces .subckt comp for "
           "sim/comp_xcheck.py} -600 -400 0 0 0.4 0.4 {}",
           "C {comp.sym} 0 0 0 0 {name=XCOMP1}"]
    labs = [("INP", -140, -40), ("INM", -140, 0), ("CLK", -140, 40),
            ("Q", 140, -40), ("QB", 140, 0), ("ON1", 140, 40),
            ("ON2", 140, 60), ("VDD", -20, -100), ("VSS", -20, 100)]
    for i, (lab, x, y) in enumerate(labs):
        out.append(f"C {{devices/lab_pin.sym}} {x} {y} 0 0 "
                   f"{{name=w{i} lab={lab.lower()}}}")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    base = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), "xschem")
    write_sch(os.path.join(base, "comp.sch"))
    write_sym(os.path.join(base, "comp.sym"))
    write_top(os.path.join(base, "comp_top.sch"))
