v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {bias: constant-gm bias generator + cascoded reference mirrors - GENERATED by tools/gen_sch.py from sim/bias_tb.py sizes - do not edit by hand} -1400 -1000 0 0 0.4 0.4 {}
T {beta-multiplier master (RB 4.6k), startup-with-disable, VBNC/VBPC from R ratios; poly-R/MiM devices, ngspice-model-calibrated lengths} -1400 -960 0 0 0.3 0.3 {}
C {devices/opin.sym} -1400 -900 0 0 {name=pp0 lab=IREFP}
C {devices/opin.sym} -1280 -900 0 0 {name=pp1 lab=IREFN}
C {devices/opin.sym} -1160 -900 0 0 {name=pp2 lab=VBNC}
C {devices/opin.sym} -1040 -900 0 0 {name=pp3 lab=VBPC}
C {devices/iopin.sym} -920 -900 0 0 {name=pp4 lab=VDD}
C {devices/iopin.sym} -800 -900 0 0 {name=pp5 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1400 -800 0 0 {name=XMP1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1380 -800 -1355 -800 {lab=VDD}
C {devices/lab_pin.sym} -1380 -770 1 0 {name=l0 lab=nb}
C {devices/lab_pin.sym} -1420 -800 0 0 {name=l1 lab=pb}
C {devices/lab_pin.sym} -1380 -830 3 0 {name=l2 lab=VDD}
C {devices/lab_pin.sym} -1355 -800 2 0 {name=l3 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1250 -800 0 0 {name=XMP2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1230 -800 -1205 -800 {lab=VDD}
C {devices/lab_pin.sym} -1230 -770 1 0 {name=l4 lab=pb}
C {devices/lab_pin.sym} -1270 -800 0 0 {name=l5 lab=pb}
C {devices/lab_pin.sym} -1230 -830 3 0 {name=l6 lab=VDD}
C {devices/lab_pin.sym} -1205 -800 2 0 {name=l7 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1400 -500 0 0 {name=XM1 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1380 -500 -1355 -500 {lab=VSS}
C {devices/lab_pin.sym} -1380 -530 1 0 {name=l8 lab=nb}
C {devices/lab_pin.sym} -1420 -500 0 0 {name=l9 lab=nb}
C {devices/lab_pin.sym} -1380 -470 3 0 {name=l10 lab=VSS}
C {devices/lab_pin.sym} -1355 -500 2 0 {name=l11 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1250 -500 0 0 {name=XM2 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=8 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1230 -500 -1205 -500 {lab=VSS}
C {devices/lab_pin.sym} -1230 -530 1 0 {name=l12 lab=pb}
C {devices/lab_pin.sym} -1270 -500 0 0 {name=l13 lab=nb}
C {devices/lab_pin.sym} -1230 -470 3 0 {name=l14 lab=rs}
C {devices/lab_pin.sym} -1205 -500 2 0 {name=l15 lab=VSS}
C {sky130_fd_pr/res_high_po_1p41.sym} -1250 -350 0 0 {name=RB model=res_high_po_1p41 spiceprefix=X L=18.88 mult=1}
C {devices/lab_pin.sym} -1250 -320 3 0 {name=l16 lab=VSS}
C {devices/lab_pin.sym} -1250 -380 1 0 {name=l17 lab=rs}
C {devices/lab_pin.sym} -1270 -350 0 0 {name=l18 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1100 -800 0 0 {name=XST model=pfet_g5v0d10v5 spiceprefix=X W=5 L=50 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1080 -800 -1055 -800 {lab=VDD}
C {devices/lab_pin.sym} -1080 -770 1 0 {name=l19 lab=nst}
C {devices/lab_pin.sym} -1120 -800 0 0 {name=l20 lab=VSS}
C {devices/lab_pin.sym} -1080 -830 3 0 {name=l21 lab=VDD}
C {devices/lab_pin.sym} -1055 -800 2 0 {name=l22 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1100 -650 0 0 {name=XFD model=pfet_g5v0d10v5 spiceprefix=X W=5 L=2 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1080 -650 -1055 -650 {lab=VDD}
C {devices/lab_pin.sym} -1080 -620 1 0 {name=l23 lab=nb}
C {devices/lab_pin.sym} -1120 -650 0 0 {name=l24 lab=VSS}
C {devices/lab_pin.sym} -1080 -680 3 0 {name=l25 lab=nst}
C {devices/lab_pin.sym} -1055 -650 2 0 {name=l26 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1100 -500 0 0 {name=XSW model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1080 -500 -1055 -500 {lab=VSS}
C {devices/lab_pin.sym} -1080 -530 1 0 {name=l27 lab=nst}
C {devices/lab_pin.sym} -1120 -500 0 0 {name=l28 lab=vbnc_i}
C {devices/lab_pin.sym} -1080 -470 3 0 {name=l29 lab=VSS}
C {devices/lab_pin.sym} -1055 -500 2 0 {name=l30 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -900 -800 0 0 {name=XIN model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=34 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -880 -800 -855 -800 {lab=VDD}
C {devices/lab_pin.sym} -880 -770 1 0 {name=l31 lab=ind}
C {devices/lab_pin.sym} -920 -800 0 0 {name=l32 lab=pb}
C {devices/lab_pin.sym} -880 -830 3 0 {name=l33 lab=VDD}
C {devices/lab_pin.sym} -855 -800 2 0 {name=l34 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -900 -650 0 0 {name=XINC model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=34 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -880 -650 -855 -650 {lab=VDD}
C {devices/lab_pin.sym} -880 -620 1 0 {name=l35 lab=IREFN}
C {devices/lab_pin.sym} -920 -650 0 0 {name=l36 lab=vbpc_i}
C {devices/lab_pin.sym} -880 -680 3 0 {name=l37 lab=ind}
C {devices/lab_pin.sym} -855 -650 2 0 {name=l38 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -900 -500 0 0 {name=XIPC model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=38 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -880 -500 -855 -500 {lab=VSS}
C {devices/lab_pin.sym} -880 -530 1 0 {name=l39 lab=IREFP}
C {devices/lab_pin.sym} -920 -500 0 0 {name=l40 lab=vbnc_i}
C {devices/lab_pin.sym} -880 -470 3 0 {name=l41 lab=ipd}
C {devices/lab_pin.sym} -855 -500 2 0 {name=l42 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -900 -350 0 0 {name=XIP model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=38 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -880 -350 -855 -350 {lab=VSS}
C {devices/lab_pin.sym} -880 -380 1 0 {name=l43 lab=ipd}
C {devices/lab_pin.sym} -920 -350 0 0 {name=l44 lab=nb}
C {devices/lab_pin.sym} -880 -320 3 0 {name=l45 lab=VSS}
C {devices/lab_pin.sym} -855 -350 2 0 {name=l46 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -700 -800 0 0 {name=XVN model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -680 -800 -655 -800 {lab=VDD}
C {devices/lab_pin.sym} -680 -770 1 0 {name=l47 lab=vbnc_i}
C {devices/lab_pin.sym} -720 -800 0 0 {name=l48 lab=pb}
C {devices/lab_pin.sym} -680 -830 3 0 {name=l49 lab=VDD}
C {devices/lab_pin.sym} -655 -800 2 0 {name=l50 lab=VDD}
C {sky130_fd_pr/res_high_po_1p41.sym} -700 -650 0 0 {name=RBNC model=res_high_po_1p41 spiceprefix=X L=324.88 mult=1}
C {devices/lab_pin.sym} -700 -620 3 0 {name=l51 lab=VSS}
C {devices/lab_pin.sym} -700 -680 1 0 {name=l52 lab=vbnc_i}
C {devices/lab_pin.sym} -720 -650 0 0 {name=l53 lab=VSS}
C {sky130_fd_pr/res_high_po_1p41.sym} -700 -500 0 0 {name=RNB1 model=res_high_po_1p41 spiceprefix=X L=3.235 mult=1}
C {devices/lab_pin.sym} -700 -470 3 0 {name=l54 lab=VBNC}
C {devices/lab_pin.sym} -700 -530 1 0 {name=l55 lab=vbnc_i}
C {devices/lab_pin.sym} -720 -500 0 0 {name=l56 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -500 -800 0 0 {name=XVP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -480 -800 -455 -800 {lab=VDD}
C {devices/lab_pin.sym} -480 -770 1 0 {name=l57 lab=vbpc_i}
C {devices/lab_pin.sym} -520 -800 0 0 {name=l58 lab=pb}
C {devices/lab_pin.sym} -480 -830 3 0 {name=l59 lab=VDD}
C {devices/lab_pin.sym} -455 -800 2 0 {name=l60 lab=VDD}
C {sky130_fd_pr/res_high_po_1p41.sym} -500 -650 0 0 {name=RBPC model=res_high_po_1p41 spiceprefix=X L=107.55 mult=1}
C {devices/lab_pin.sym} -500 -620 3 0 {name=l61 lab=VSS}
C {devices/lab_pin.sym} -500 -680 1 0 {name=l62 lab=vbpc_i}
C {devices/lab_pin.sym} -520 -650 0 0 {name=l63 lab=VSS}
C {sky130_fd_pr/res_high_po_1p41.sym} -500 -500 0 0 {name=RNB2 model=res_high_po_1p41 spiceprefix=X L=3.235 mult=1}
C {devices/lab_pin.sym} -500 -470 3 0 {name=l64 lab=VBPC}
C {devices/lab_pin.sym} -500 -530 1 0 {name=l65 lab=vbpc_i}
C {devices/lab_pin.sym} -520 -500 0 0 {name=l66 lab=VSS}
N -1380 -770 -1380 -530 {lab=nb}
N -1230 -770 -1230 -530 {lab=pb}
N -1080 -770 -1080 -680 {lab=nst}
N -880 -770 -880 -680 {lab=ind}
N -880 -470 -880 -380 {lab=ipd}
N -680 -770 -700 -680 {lab=vbnc_i}
N -480 -770 -500 -680 {lab=vbpc_i}
