v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {buf: 5T unity-follower reference buffer - GENERATED by tools/gen_sch.py from sim/buf_tb.py sizes - do not edit by hand} -1400 -1000 0 0 0.4 0.4 {}
T {PMOS input, NMOS mirror load, tail mult 64 off the OTA IREFP diode line (5 uA/finger); one design, three instances (VREFN/VCM/VREFP)} -1400 -960 0 0 0.3 0.3 {}
C {devices/ipin.sym} -1400 -900 0 0 {name=pp0 lab=IN}
C {devices/opin.sym} -1280 -900 0 0 {name=pp1 lab=OUT}
C {devices/ipin.sym} -1160 -900 0 0 {name=pp2 lab=IREFP}
C {devices/iopin.sym} -1040 -900 0 0 {name=pp3 lab=VDD}
C {devices/iopin.sym} -920 -900 0 0 {name=pp4 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -300 -800 0 0 {name=XT model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=64 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -280 -800 -255 -800 {lab=VDD}
C {devices/lab_pin.sym} -280 -770 1 0 {name=l0 lab=tail}
C {devices/lab_pin.sym} -320 -800 0 0 {name=l1 lab=IREFP}
C {devices/lab_pin.sym} -280 -830 3 0 {name=l2 lab=VDD}
C {devices/lab_pin.sym} -255 -800 2 0 {name=l3 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -400 -650 0 0 {name=X1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -380 -650 -355 -650 {lab=VDD}
C {devices/lab_pin.sym} -380 -620 1 0 {name=l4 lab=o1}
C {devices/lab_pin.sym} -420 -650 0 0 {name=l5 lab=IN}
C {devices/lab_pin.sym} -380 -680 3 0 {name=l6 lab=tail}
C {devices/lab_pin.sym} -355 -650 2 0 {name=l7 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -200 -650 0 0 {name=X2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -650 -155 -650 {lab=VDD}
C {devices/lab_pin.sym} -180 -620 1 0 {name=l8 lab=OUT}
C {devices/lab_pin.sym} -220 -650 0 0 {name=l9 lab=OUT}
C {devices/lab_pin.sym} -180 -680 3 0 {name=l10 lab=tail}
C {devices/lab_pin.sym} -155 -650 2 0 {name=l11 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -400 -450 0 0 {name=X3 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=6 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -380 -450 -355 -450 {lab=VSS}
C {devices/lab_pin.sym} -380 -480 1 0 {name=l12 lab=o1}
C {devices/lab_pin.sym} -420 -450 0 0 {name=l13 lab=o1}
C {devices/lab_pin.sym} -380 -420 3 0 {name=l14 lab=VSS}
C {devices/lab_pin.sym} -355 -450 2 0 {name=l15 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -200 -450 0 0 {name=X4 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=6 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -450 -155 -450 {lab=VSS}
C {devices/lab_pin.sym} -180 -480 1 0 {name=l16 lab=OUT}
C {devices/lab_pin.sym} -220 -450 0 0 {name=l17 lab=o1}
C {devices/lab_pin.sym} -180 -420 3 0 {name=l18 lab=VSS}
C {devices/lab_pin.sym} -155 -450 2 0 {name=l19 lab=VSS}
N -280 -770 -280 -700 {lab=tail}
N -380 -700 -180 -700 {lab=tail}
N -380 -680 -380 -700 {lab=tail}
N -180 -680 -180 -700 {lab=tail}
N -380 -620 -380 -480 {lab=o1}
N -180 -620 -180 -480 {lab=OUT}
