v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {StrongARM comparator - GENERATED by tools/gen_comp_sch.py from sim/comp_tb.py SIZES - do not edit by hand} -1400 -1000 0 0 0.4 0.4 {}
T {PMOS input (senses the low window - DESIGN.md open item 6), evaluates CLK low, precharge to VSS, NOR SR latch; unit finger W=5 L=0.5} -1400 -960 0 0 0.3 0.3 {}
C {devices/ipin.sym} -1400 -900 0 0 {name=pp0 lab=INP}
C {devices/ipin.sym} -1280 -900 0 0 {name=pp1 lab=INM}
C {devices/ipin.sym} -1160 -900 0 0 {name=pp2 lab=CLK}
C {devices/opin.sym} -1040 -900 0 0 {name=pp3 lab=Q}
C {devices/opin.sym} -920 -900 0 0 {name=pp4 lab=QB}
C {devices/opin.sym} -800 -900 0 0 {name=pp5 lab=ON1}
C {devices/opin.sym} -680 -900 0 0 {name=pp6 lab=ON2}
C {devices/iopin.sym} -560 -900 0 0 {name=pp7 lab=VDD}
C {devices/iopin.sym} -440 -900 0 0 {name=pp8 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1100 -800 0 0 {name=XT model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1080 -770 1 0 {name=l0 lab=tail}
C {devices/lab_pin.sym} -1120 -800 0 0 {name=l1 lab=CLK}
C {devices/lab_pin.sym} -1080 -830 3 0 {name=l2 lab=VDD}
C {devices/lab_pin.sym} -1055 -800 2 0 {name=l3 lab=VDD}
N -1080 -800 -1055 -800 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1250 -650 0 0 {name=X1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1230 -620 1 0 {name=l4 lab=di1}
C {devices/lab_pin.sym} -1270 -650 0 0 {name=l5 lab=INP}
C {devices/lab_pin.sym} -1230 -680 3 0 {name=l6 lab=tail}
C {devices/lab_pin.sym} -1205 -650 2 0 {name=l7 lab=VDD}
N -1230 -650 -1205 -650 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -950 -650 0 0 {name=X2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -930 -620 1 0 {name=l8 lab=di2}
C {devices/lab_pin.sym} -970 -650 0 0 {name=l9 lab=INM}
C {devices/lab_pin.sym} -930 -680 3 0 {name=l10 lab=tail}
C {devices/lab_pin.sym} -905 -650 2 0 {name=l11 lab=VDD}
N -930 -650 -905 -650 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1250 -500 0 0 {name=X3 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1230 -470 1 0 {name=l12 lab=ON1}
C {devices/lab_pin.sym} -1270 -500 0 0 {name=l13 lab=ON2}
C {devices/lab_pin.sym} -1230 -530 3 0 {name=l14 lab=di1}
C {devices/lab_pin.sym} -1205 -500 2 0 {name=l15 lab=VDD}
N -1230 -500 -1205 -500 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -950 -500 0 0 {name=X4 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -930 -470 1 0 {name=l16 lab=ON2}
C {devices/lab_pin.sym} -970 -500 0 0 {name=l17 lab=ON1}
C {devices/lab_pin.sym} -930 -530 3 0 {name=l18 lab=di2}
C {devices/lab_pin.sym} -905 -500 2 0 {name=l19 lab=VDD}
N -930 -500 -905 -500 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1250 -350 0 0 {name=X5 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1230 -380 1 0 {name=l20 lab=ON1}
C {devices/lab_pin.sym} -1270 -350 0 0 {name=l21 lab=ON2}
C {devices/lab_pin.sym} -1230 -320 3 0 {name=l22 lab=VSS}
C {devices/lab_pin.sym} -1205 -350 2 0 {name=l23 lab=VSS}
N -1230 -350 -1205 -350 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -950 -350 0 0 {name=X6 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -930 -380 1 0 {name=l24 lab=ON2}
C {devices/lab_pin.sym} -970 -350 0 0 {name=l25 lab=ON1}
C {devices/lab_pin.sym} -930 -320 3 0 {name=l26 lab=VSS}
C {devices/lab_pin.sym} -905 -350 2 0 {name=l27 lab=VSS}
N -930 -350 -905 -350 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1250 -200 0 0 {name=XR1 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1230 -230 1 0 {name=l28 lab=di1}
C {devices/lab_pin.sym} -1270 -200 0 0 {name=l29 lab=CLK}
C {devices/lab_pin.sym} -1230 -170 3 0 {name=l30 lab=VSS}
C {devices/lab_pin.sym} -1205 -200 2 0 {name=l31 lab=VSS}
N -1230 -200 -1205 -200 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1100 -200 0 0 {name=XR2 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -1080 -230 1 0 {name=l32 lab=di2}
C {devices/lab_pin.sym} -1120 -200 0 0 {name=l33 lab=CLK}
C {devices/lab_pin.sym} -1080 -170 3 0 {name=l34 lab=VSS}
C {devices/lab_pin.sym} -1055 -200 2 0 {name=l35 lab=VSS}
N -1080 -200 -1055 -200 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -950 -200 0 0 {name=XR3 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -930 -230 1 0 {name=l36 lab=ON1}
C {devices/lab_pin.sym} -970 -200 0 0 {name=l37 lab=CLK}
C {devices/lab_pin.sym} -930 -170 3 0 {name=l38 lab=VSS}
C {devices/lab_pin.sym} -905 -200 2 0 {name=l39 lab=VSS}
N -930 -200 -905 -200 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -800 -200 0 0 {name=XR4 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -780 -230 1 0 {name=l40 lab=ON2}
C {devices/lab_pin.sym} -820 -200 0 0 {name=l41 lab=CLK}
C {devices/lab_pin.sym} -780 -170 3 0 {name=l42 lab=VSS}
C {devices/lab_pin.sym} -755 -200 2 0 {name=l43 lab=VSS}
N -780 -200 -755 -200 {lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -650 -800 0 0 {name=XI1P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -770 1 0 {name=l44 lab=n1b}
C {devices/lab_pin.sym} -670 -800 0 0 {name=l45 lab=ON1}
C {devices/lab_pin.sym} -630 -830 3 0 {name=l46 lab=VDD}
C {devices/lab_pin.sym} -605 -800 2 0 {name=l47 lab=VDD}
N -630 -800 -605 -800 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -650 -650 0 0 {name=XI1N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -680 1 0 {name=l48 lab=n1b}
C {devices/lab_pin.sym} -670 -650 0 0 {name=l49 lab=ON1}
C {devices/lab_pin.sym} -630 -620 3 0 {name=l50 lab=VSS}
C {devices/lab_pin.sym} -605 -650 2 0 {name=l51 lab=VSS}
N -630 -650 -605 -650 {lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -650 -500 0 0 {name=XI2P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -470 1 0 {name=l52 lab=n2b}
C {devices/lab_pin.sym} -670 -500 0 0 {name=l53 lab=ON2}
C {devices/lab_pin.sym} -630 -530 3 0 {name=l54 lab=VDD}
C {devices/lab_pin.sym} -605 -500 2 0 {name=l55 lab=VDD}
N -630 -500 -605 -500 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -650 -350 0 0 {name=XI2N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -380 1 0 {name=l56 lab=n2b}
C {devices/lab_pin.sym} -670 -350 0 0 {name=l57 lab=ON2}
C {devices/lab_pin.sym} -630 -320 3 0 {name=l58 lab=VSS}
C {devices/lab_pin.sym} -605 -350 2 0 {name=l59 lab=VSS}
N -630 -350 -605 -350 {lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -450 -800 0 0 {name=XAQ1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -430 -770 1 0 {name=l60 lab=Q}
C {devices/lab_pin.sym} -470 -800 0 0 {name=l61 lab=n2b}
C {devices/lab_pin.sym} -430 -830 3 0 {name=l62 lab=VDD}
C {devices/lab_pin.sym} -405 -800 2 0 {name=l63 lab=VDD}
N -430 -800 -405 -800 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -450 -650 0 0 {name=XAQ2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -430 -620 1 0 {name=l64 lab=Q}
C {devices/lab_pin.sym} -470 -650 0 0 {name=l65 lab=QB}
C {devices/lab_pin.sym} -430 -680 3 0 {name=l66 lab=VDD}
C {devices/lab_pin.sym} -405 -650 2 0 {name=l67 lab=VDD}
N -430 -650 -405 -650 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -450 -500 0 0 {name=XAQ3 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -430 -530 1 0 {name=l68 lab=Q}
C {devices/lab_pin.sym} -470 -500 0 0 {name=l69 lab=n2b}
C {devices/lab_pin.sym} -430 -470 3 0 {name=l70 lab=sq}
C {devices/lab_pin.sym} -405 -500 2 0 {name=l71 lab=VSS}
N -430 -500 -405 -500 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -450 -350 0 0 {name=XAQ4 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -430 -380 1 0 {name=l72 lab=sq}
C {devices/lab_pin.sym} -470 -350 0 0 {name=l73 lab=QB}
C {devices/lab_pin.sym} -430 -320 3 0 {name=l74 lab=VSS}
C {devices/lab_pin.sym} -405 -350 2 0 {name=l75 lab=VSS}
N -430 -350 -405 -350 {lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -150 -800 0 0 {name=XAB1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -130 -770 1 0 {name=l76 lab=QB}
C {devices/lab_pin.sym} -170 -800 0 0 {name=l77 lab=n1b}
C {devices/lab_pin.sym} -130 -830 3 0 {name=l78 lab=VDD}
C {devices/lab_pin.sym} -105 -800 2 0 {name=l79 lab=VDD}
N -130 -800 -105 -800 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -150 -650 0 0 {name=XAB2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -130 -620 1 0 {name=l80 lab=QB}
C {devices/lab_pin.sym} -170 -650 0 0 {name=l81 lab=Q}
C {devices/lab_pin.sym} -130 -680 3 0 {name=l82 lab=VDD}
C {devices/lab_pin.sym} -105 -650 2 0 {name=l83 lab=VDD}
N -130 -650 -105 -650 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -150 -500 0 0 {name=XAB3 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -130 -530 1 0 {name=l84 lab=QB}
C {devices/lab_pin.sym} -170 -500 0 0 {name=l85 lab=n1b}
C {devices/lab_pin.sym} -130 -470 3 0 {name=l86 lab=sb}
C {devices/lab_pin.sym} -105 -500 2 0 {name=l87 lab=VSS}
N -130 -500 -105 -500 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -150 -350 0 0 {name=XAB4 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -130 -380 1 0 {name=l88 lab=sb}
C {devices/lab_pin.sym} -170 -350 0 0 {name=l89 lab=Q}
C {devices/lab_pin.sym} -130 -320 3 0 {name=l90 lab=VSS}
C {devices/lab_pin.sym} -105 -350 2 0 {name=l91 lab=VSS}
N -130 -350 -105 -350 {lab=VSS}
