v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {dff: master-slave TG DFF retimer - GENERATED by tools/gen_sch.py from sim/dff_tb.py sizes - do not edit by hand} -1400 -1000 0 0 0.4 0.4 {}
T {static CMOS, master latches on rising CLK; pins Q move only at the edge; unit finger W=5 L=0.5} -1400 -960 0 0 0.3 0.3 {}
C {devices/ipin.sym} -1400 -900 0 0 {name=pp0 lab=D}
C {devices/ipin.sym} -1280 -900 0 0 {name=pp1 lab=CLK}
C {devices/opin.sym} -1160 -900 0 0 {name=pp2 lab=Q}
C {devices/opin.sym} -1040 -900 0 0 {name=pp3 lab=QB}
C {devices/iopin.sym} -920 -900 0 0 {name=pp4 lab=VDD}
C {devices/iopin.sym} -800 -900 0 0 {name=pp5 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1400 -650 0 0 {name=XICP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1380 -650 -1355 -650 {lab=VDD}
C {devices/lab_pin.sym} -1380 -620 1 0 {name=l0 lab=clkb}
C {devices/lab_pin.sym} -1420 -650 0 0 {name=l1 lab=CLK}
C {devices/lab_pin.sym} -1380 -680 3 0 {name=l2 lab=VDD}
C {devices/lab_pin.sym} -1355 -650 2 0 {name=l3 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1400 -500 0 0 {name=XICN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1380 -500 -1355 -500 {lab=VSS}
C {devices/lab_pin.sym} -1380 -530 1 0 {name=l4 lab=clkb}
C {devices/lab_pin.sym} -1420 -500 0 0 {name=l5 lab=CLK}
C {devices/lab_pin.sym} -1380 -470 3 0 {name=l6 lab=VSS}
C {devices/lab_pin.sym} -1355 -500 2 0 {name=l7 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1250 -650 0 0 {name=XTMN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1230 -650 -1205 -650 {lab=VSS}
C {devices/lab_pin.sym} -1230 -680 1 0 {name=l8 lab=D}
C {devices/lab_pin.sym} -1270 -650 0 0 {name=l9 lab=clkb}
C {devices/lab_pin.sym} -1230 -620 3 0 {name=l10 lab=mi}
C {devices/lab_pin.sym} -1205 -650 2 0 {name=l11 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1250 -500 0 0 {name=XTMP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1230 -500 -1205 -500 {lab=VDD}
C {devices/lab_pin.sym} -1230 -470 1 0 {name=l12 lab=D}
C {devices/lab_pin.sym} -1270 -500 0 0 {name=l13 lab=CLK}
C {devices/lab_pin.sym} -1230 -530 3 0 {name=l14 lab=mi}
C {devices/lab_pin.sym} -1205 -500 2 0 {name=l15 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -1100 -650 0 0 {name=XIM1P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1080 -650 -1055 -650 {lab=VDD}
C {devices/lab_pin.sym} -1080 -620 1 0 {name=l16 lab=mb}
C {devices/lab_pin.sym} -1120 -650 0 0 {name=l17 lab=mi}
C {devices/lab_pin.sym} -1080 -680 3 0 {name=l18 lab=VDD}
C {devices/lab_pin.sym} -1055 -650 2 0 {name=l19 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -1100 -500 0 0 {name=XIM1N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -1080 -500 -1055 -500 {lab=VSS}
C {devices/lab_pin.sym} -1080 -530 1 0 {name=l20 lab=mb}
C {devices/lab_pin.sym} -1120 -500 0 0 {name=l21 lab=mi}
C {devices/lab_pin.sym} -1080 -470 3 0 {name=l22 lab=VSS}
C {devices/lab_pin.sym} -1055 -500 2 0 {name=l23 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -950 -650 0 0 {name=XIM2P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -930 -650 -905 -650 {lab=VDD}
C {devices/lab_pin.sym} -930 -620 1 0 {name=l24 lab=mfb}
C {devices/lab_pin.sym} -970 -650 0 0 {name=l25 lab=mb}
C {devices/lab_pin.sym} -930 -680 3 0 {name=l26 lab=VDD}
C {devices/lab_pin.sym} -905 -650 2 0 {name=l27 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -950 -500 0 0 {name=XIM2N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -930 -500 -905 -500 {lab=VSS}
C {devices/lab_pin.sym} -930 -530 1 0 {name=l28 lab=mfb}
C {devices/lab_pin.sym} -970 -500 0 0 {name=l29 lab=mb}
C {devices/lab_pin.sym} -930 -470 3 0 {name=l30 lab=VSS}
C {devices/lab_pin.sym} -905 -500 2 0 {name=l31 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -800 -650 0 0 {name=XTMFN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -780 -650 -755 -650 {lab=VSS}
C {devices/lab_pin.sym} -780 -680 1 0 {name=l32 lab=mfb}
C {devices/lab_pin.sym} -820 -650 0 0 {name=l33 lab=CLK}
C {devices/lab_pin.sym} -780 -620 3 0 {name=l34 lab=mi}
C {devices/lab_pin.sym} -755 -650 2 0 {name=l35 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -800 -500 0 0 {name=XTMFP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -780 -500 -755 -500 {lab=VDD}
C {devices/lab_pin.sym} -780 -470 1 0 {name=l36 lab=mfb}
C {devices/lab_pin.sym} -820 -500 0 0 {name=l37 lab=clkb}
C {devices/lab_pin.sym} -780 -530 3 0 {name=l38 lab=mi}
C {devices/lab_pin.sym} -755 -500 2 0 {name=l39 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -650 -650 0 0 {name=XTSN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -630 -650 -605 -650 {lab=VSS}
C {devices/lab_pin.sym} -630 -680 1 0 {name=l40 lab=mb}
C {devices/lab_pin.sym} -670 -650 0 0 {name=l41 lab=CLK}
C {devices/lab_pin.sym} -630 -620 3 0 {name=l42 lab=si}
C {devices/lab_pin.sym} -605 -650 2 0 {name=l43 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -650 -500 0 0 {name=XTSP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -630 -500 -605 -500 {lab=VDD}
C {devices/lab_pin.sym} -630 -470 1 0 {name=l44 lab=mb}
C {devices/lab_pin.sym} -670 -500 0 0 {name=l45 lab=clkb}
C {devices/lab_pin.sym} -630 -530 3 0 {name=l46 lab=si}
C {devices/lab_pin.sym} -605 -500 2 0 {name=l47 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -500 -650 0 0 {name=XIS1P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -480 -650 -455 -650 {lab=VDD}
C {devices/lab_pin.sym} -480 -620 1 0 {name=l48 lab=QB}
C {devices/lab_pin.sym} -520 -650 0 0 {name=l49 lab=si}
C {devices/lab_pin.sym} -480 -680 3 0 {name=l50 lab=VDD}
C {devices/lab_pin.sym} -455 -650 2 0 {name=l51 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -500 -500 0 0 {name=XIS1N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -480 -500 -455 -500 {lab=VSS}
C {devices/lab_pin.sym} -480 -530 1 0 {name=l52 lab=QB}
C {devices/lab_pin.sym} -520 -500 0 0 {name=l53 lab=si}
C {devices/lab_pin.sym} -480 -470 3 0 {name=l54 lab=VSS}
C {devices/lab_pin.sym} -455 -500 2 0 {name=l55 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -350 -650 0 0 {name=XIS2P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -330 -650 -305 -650 {lab=VDD}
C {devices/lab_pin.sym} -330 -620 1 0 {name=l56 lab=sfb}
C {devices/lab_pin.sym} -370 -650 0 0 {name=l57 lab=QB}
C {devices/lab_pin.sym} -330 -680 3 0 {name=l58 lab=VDD}
C {devices/lab_pin.sym} -305 -650 2 0 {name=l59 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -350 -500 0 0 {name=XIS2N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -330 -500 -305 -500 {lab=VSS}
C {devices/lab_pin.sym} -330 -530 1 0 {name=l60 lab=sfb}
C {devices/lab_pin.sym} -370 -500 0 0 {name=l61 lab=QB}
C {devices/lab_pin.sym} -330 -470 3 0 {name=l62 lab=VSS}
C {devices/lab_pin.sym} -305 -500 2 0 {name=l63 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -200 -650 0 0 {name=XTSFN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -650 -155 -650 {lab=VSS}
C {devices/lab_pin.sym} -180 -680 1 0 {name=l64 lab=sfb}
C {devices/lab_pin.sym} -220 -650 0 0 {name=l65 lab=clkb}
C {devices/lab_pin.sym} -180 -620 3 0 {name=l66 lab=si}
C {devices/lab_pin.sym} -155 -650 2 0 {name=l67 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -200 -500 0 0 {name=XTSFP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -500 -155 -500 {lab=VDD}
C {devices/lab_pin.sym} -180 -470 1 0 {name=l68 lab=sfb}
C {devices/lab_pin.sym} -220 -500 0 0 {name=l69 lab=CLK}
C {devices/lab_pin.sym} -180 -530 3 0 {name=l70 lab=si}
C {devices/lab_pin.sym} -155 -500 2 0 {name=l71 lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -50 -650 0 0 {name=XIQ1P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -30 -650 -5 -650 {lab=VDD}
C {devices/lab_pin.sym} -30 -620 1 0 {name=l72 lab=Q}
C {devices/lab_pin.sym} -70 -650 0 0 {name=l73 lab=QB}
C {devices/lab_pin.sym} -30 -680 3 0 {name=l74 lab=VDD}
C {devices/lab_pin.sym} -5 -650 2 0 {name=l75 lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -50 -500 0 0 {name=XIQ1N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -30 -500 -5 -500 {lab=VSS}
C {devices/lab_pin.sym} -30 -530 1 0 {name=l76 lab=Q}
C {devices/lab_pin.sym} -70 -500 0 0 {name=l77 lab=QB}
C {devices/lab_pin.sym} -30 -470 3 0 {name=l78 lab=VSS}
C {devices/lab_pin.sym} -5 -500 2 0 {name=l79 lab=VSS}
N -1380 -620 -1380 -530 {lab=clkb}
N -1080 -620 -1080 -530 {lab=mb}
N -930 -620 -930 -530 {lab=mfb}
N -480 -620 -480 -530 {lab=QB}
N -330 -620 -330 -530 {lab=sfb}
N -30 -620 -30 -530 {lab=Q}
N -1230 -620 -1230 -530 {lab=mi}
N -780 -620 -780 -530 {lab=mi}
N -630 -620 -630 -530 {lab=si}
N -180 -620 -180 -530 {lab=si}
