v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {lvl: cross-coupled 1.8->3.3 V clock level shifter - GENERATED by tools/gen_sch.py from sim/lvl_tb.py sizes - do not edit by hand} -1400 -1000 0 0 0.4 0.4 {}
T {thin-oxide input inverter on VDPWR, strong 5V pulldowns vs weak cross-coupled PMOS, buffered complementary outputs} -1400 -960 0 0 0.3 0.3 {}
C {devices/ipin.sym} -1400 -900 0 0 {name=pp0 lab=CLK18}
C {devices/opin.sym} -1280 -900 0 0 {name=pp1 lab=CLK33}
C {devices/opin.sym} -1160 -900 0 0 {name=pp2 lab=CLKB33}
C {devices/iopin.sym} -1040 -900 0 0 {name=pp3 lab=VDD18}
C {devices/iopin.sym} -920 -900 0 0 {name=pp4 lab=VDD33}
C {devices/iopin.sym} -800 -900 0 0 {name=pp5 lab=VSS}
C {sky130_fd_pr/pfet_01v8.sym} -1000 -650 0 0 {name=XIP model=pfet_01v8 spiceprefix=X W=10 L=0.35 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -980 -650 -955 -650 {lab=VDD18}
C {devices/lab_pin.sym} -980 -620 1 0 {name=l0 lab=nb18}
C {devices/lab_pin.sym} -1020 -650 0 0 {name=l1 lab=CLK18}
C {devices/lab_pin.sym} -980 -680 3 0 {name=l2 lab=VDD18}
C {devices/lab_pin.sym} -955 -650 2 0 {name=l3 lab=VDD18}
C {sky130_fd_pr/nfet_01v8.sym} -1000 -500 0 0 {name=XIN model=nfet_01v8 spiceprefix=X W=5 L=0.35 nf=1 mult=1 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -980 -500 -955 -500 {lab=VSS}
C {devices/lab_pin.sym} -980 -530 1 0 {name=l4 lab=nb18}
C {devices/lab_pin.sym} -1020 -500 0 0 {name=l5 lab=CLK18}
C {devices/lab_pin.sym} -980 -470 3 0 {name=l6 lab=VSS}
C {devices/lab_pin.sym} -955 -500 2 0 {name=l7 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -800 -650 0 0 {name=XP1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -780 -650 -755 -650 {lab=VDD33}
C {devices/lab_pin.sym} -780 -620 1 0 {name=l8 lab=n1}
C {devices/lab_pin.sym} -820 -650 0 0 {name=l9 lab=n2}
C {devices/lab_pin.sym} -780 -680 3 0 {name=l10 lab=VDD33}
C {devices/lab_pin.sym} -755 -650 2 0 {name=l11 lab=VDD33}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -600 -650 0 0 {name=XP2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -580 -650 -555 -650 {lab=VDD33}
C {devices/lab_pin.sym} -580 -620 1 0 {name=l12 lab=n2}
C {devices/lab_pin.sym} -620 -650 0 0 {name=l13 lab=n1}
C {devices/lab_pin.sym} -580 -680 3 0 {name=l14 lab=VDD33}
C {devices/lab_pin.sym} -555 -650 2 0 {name=l15 lab=VDD33}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -800 -500 0 0 {name=XN1 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=8 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -780 -500 -755 -500 {lab=VSS}
C {devices/lab_pin.sym} -780 -530 1 0 {name=l16 lab=n1}
C {devices/lab_pin.sym} -820 -500 0 0 {name=l17 lab=CLK18}
C {devices/lab_pin.sym} -780 -470 3 0 {name=l18 lab=VSS}
C {devices/lab_pin.sym} -755 -500 2 0 {name=l19 lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -600 -500 0 0 {name=XN2 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=8 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -580 -500 -555 -500 {lab=VSS}
C {devices/lab_pin.sym} -580 -530 1 0 {name=l20 lab=n2}
C {devices/lab_pin.sym} -620 -500 0 0 {name=l21 lab=nb18}
C {devices/lab_pin.sym} -580 -470 3 0 {name=l22 lab=VSS}
C {devices/lab_pin.sym} -555 -500 2 0 {name=l23 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -400 -650 0 0 {name=XB1P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -380 -650 -355 -650 {lab=VDD33}
C {devices/lab_pin.sym} -380 -620 1 0 {name=l24 lab=CLK33}
C {devices/lab_pin.sym} -420 -650 0 0 {name=l25 lab=n1}
C {devices/lab_pin.sym} -380 -680 3 0 {name=l26 lab=VDD33}
C {devices/lab_pin.sym} -355 -650 2 0 {name=l27 lab=VDD33}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -400 -500 0 0 {name=XB1N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -380 -500 -355 -500 {lab=VSS}
C {devices/lab_pin.sym} -380 -530 1 0 {name=l28 lab=CLK33}
C {devices/lab_pin.sym} -420 -500 0 0 {name=l29 lab=n1}
C {devices/lab_pin.sym} -380 -470 3 0 {name=l30 lab=VSS}
C {devices/lab_pin.sym} -355 -500 2 0 {name=l31 lab=VSS}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -200 -650 0 0 {name=XB2P model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -650 -155 -650 {lab=VDD33}
C {devices/lab_pin.sym} -180 -620 1 0 {name=l32 lab=CLKB33}
C {devices/lab_pin.sym} -220 -650 0 0 {name=l33 lab=n2}
C {devices/lab_pin.sym} -180 -680 3 0 {name=l34 lab=VDD33}
C {devices/lab_pin.sym} -155 -650 2 0 {name=l35 lab=VDD33}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -200 -500 0 0 {name=XB2N model=nfet_g5v0d10v5 spiceprefix=X W=5 L=0.5 nf=1 mult=2 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
N -180 -500 -155 -500 {lab=VSS}
C {devices/lab_pin.sym} -180 -530 1 0 {name=l36 lab=CLKB33}
C {devices/lab_pin.sym} -220 -500 0 0 {name=l37 lab=n2}
C {devices/lab_pin.sym} -180 -470 3 0 {name=l38 lab=VSS}
C {devices/lab_pin.sym} -155 -500 2 0 {name=l39 lab=VSS}
N -980 -620 -980 -530 {lab=nb18}
N -780 -620 -780 -530 {lab=n1}
N -580 -620 -580 -530 {lab=n2}
N -380 -620 -380 -530 {lab=CLK33}
N -180 -620 -180 -530 {lab=CLKB33}
