v {xschem version=3.4.4 file_version=1.2}
G {}
K {}
V {}
S {}
E {}
T {folded-cascode OTA - GENERATED by tools/gen_ota_sch.py from sim/ota_tb.py SIZES - do not edit by hand} -1500 -1000 0 0 0.4 0.4 {}
T {PMOS mirror / cascodes (top), NMOS cascodes / sinks (bottom); left column = bias diodes; unit finger W=5} -1500 -960 0 0 0.3 0.3 {}
C {devices/ipin.sym} -1500 -900 0 0 {name=pp0 lab=INP}
C {devices/ipin.sym} -1380 -900 0 0 {name=pp1 lab=INM}
C {devices/opin.sym} -1260 -900 0 0 {name=pp2 lab=OUT}
C {devices/iopin.sym} -1140 -900 0 0 {name=pp3 lab=VDD}
C {devices/iopin.sym} -1020 -900 0 0 {name=pp4 lab=VSS}
C {devices/ipin.sym} -900 -900 0 0 {name=pp5 lab=IREFP}
C {devices/ipin.sym} -780 -900 0 0 {name=pp6 lab=IREFN}
C {devices/ipin.sym} -660 -900 0 0 {name=pp7 lab=VBNC}
C {devices/ipin.sym} -540 -900 0 0 {name=pp8 lab=VBPC}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -900 -800 0 0 {name=MDP model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=76 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -880 -770 1 0 {name=l0 lab=IREFP}
C {devices/lab_pin.sym} -920 -800 0 0 {name=l1 lab=IREFP}
C {devices/lab_pin.sym} -880 -830 3 0 {name=l2 lab=VDD}
C {devices/lab_pin.sym} -855 -800 2 0 {name=l3 lab=VDD}
N -880 -800 -855 -800 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -650 -800 0 0 {name=MT model=pfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=76 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -770 1 0 {name=l4 lab=tail}
C {devices/lab_pin.sym} -670 -800 0 0 {name=l5 lab=IREFP}
C {devices/lab_pin.sym} -630 -830 3 0 {name=l6 lab=VDD}
C {devices/lab_pin.sym} -605 -800 2 0 {name=l7 lab=VDD}
N -630 -800 -605 -800 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -650 -650 0 0 {name=M1 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=50 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -630 -620 1 0 {name=l8 lab=fn1}
C {devices/lab_pin.sym} -670 -650 0 0 {name=l9 lab=INP}
C {devices/lab_pin.sym} -630 -680 3 0 {name=l10 lab=tail}
C {devices/lab_pin.sym} -605 -650 2 0 {name=l11 lab=tail}
N -630 -650 -605 -650 {lab=tail}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -450 -650 0 0 {name=M2 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=50 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -430 -620 1 0 {name=l12 lab=fn2}
C {devices/lab_pin.sym} -470 -650 0 0 {name=l13 lab=INM}
C {devices/lab_pin.sym} -430 -680 3 0 {name=l14 lab=tail}
C {devices/lab_pin.sym} -405 -650 2 0 {name=l15 lab=tail}
N -430 -650 -405 -650 {lab=tail}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -300 -600 0 0 {name=M9 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -280 -570 1 0 {name=l16 lab=pc1}
C {devices/lab_pin.sym} -320 -600 0 0 {name=l17 lab=dio}
C {devices/lab_pin.sym} -280 -630 3 0 {name=l18 lab=VDD}
C {devices/lab_pin.sym} -255 -600 2 0 {name=l19 lab=VDD}
N -280 -600 -255 -600 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} 0 -600 0 0 {name=M10 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} 20 -570 1 0 {name=l20 lab=pc2}
C {devices/lab_pin.sym} -20 -600 0 0 {name=l21 lab=dio}
C {devices/lab_pin.sym} 20 -630 3 0 {name=l22 lab=VDD}
C {devices/lab_pin.sym} 45 -600 2 0 {name=l23 lab=VDD}
N 20 -600 45 -600 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} -300 -450 0 0 {name=M7 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -280 -420 1 0 {name=l24 lab=dio}
C {devices/lab_pin.sym} -320 -450 0 0 {name=l25 lab=VBPC}
C {devices/lab_pin.sym} -280 -480 3 0 {name=l26 lab=pc1}
C {devices/lab_pin.sym} -255 -450 2 0 {name=l27 lab=VDD}
N -280 -450 -255 -450 {lab=VDD}
C {sky130_fd_pr/pfet_g5v0d10v5.sym} 0 -450 0 0 {name=M8 model=pfet_g5v0d10v5 spiceprefix=X W=5 L=0.7 nf=1 mult=12 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} 20 -420 1 0 {name=l28 lab=OUT}
C {devices/lab_pin.sym} -20 -450 0 0 {name=l29 lab=VBPC}
C {devices/lab_pin.sym} 20 -480 3 0 {name=l30 lab=pc2}
C {devices/lab_pin.sym} 45 -450 2 0 {name=l31 lab=VDD}
N 20 -450 45 -450 {lab=VDD}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -300 -300 0 0 {name=M5 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=24 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -280 -330 1 0 {name=l32 lab=dio}
C {devices/lab_pin.sym} -320 -300 0 0 {name=l33 lab=VBNC}
C {devices/lab_pin.sym} -280 -270 3 0 {name=l34 lab=fn1}
C {devices/lab_pin.sym} -255 -300 2 0 {name=l35 lab=VSS}
N -280 -300 -255 -300 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} 0 -300 0 0 {name=M6 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1 nf=1 mult=24 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} 20 -330 1 0 {name=l36 lab=OUT}
C {devices/lab_pin.sym} -20 -300 0 0 {name=l37 lab=VBNC}
C {devices/lab_pin.sym} 20 -270 3 0 {name=l38 lab=fn2}
C {devices/lab_pin.sym} 45 -300 2 0 {name=l39 lab=VSS}
N 20 -300 45 -300 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -300 -150 0 0 {name=M3 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1.2 nf=1 mult=24 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -280 -180 1 0 {name=l40 lab=fn1}
C {devices/lab_pin.sym} -320 -150 0 0 {name=l41 lab=IREFN}
C {devices/lab_pin.sym} -280 -120 3 0 {name=l42 lab=VSS}
C {devices/lab_pin.sym} -255 -150 2 0 {name=l43 lab=VSS}
N -280 -150 -255 -150 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} 0 -150 0 0 {name=M4 model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1.2 nf=1 mult=24 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} 20 -180 1 0 {name=l44 lab=fn2}
C {devices/lab_pin.sym} -20 -150 0 0 {name=l45 lab=IREFN}
C {devices/lab_pin.sym} 20 -120 3 0 {name=l46 lab=VSS}
C {devices/lab_pin.sym} 45 -150 2 0 {name=l47 lab=VSS}
N 20 -150 45 -150 {lab=VSS}
C {sky130_fd_pr/nfet_g5v0d10v5.sym} -900 -150 0 0 {name=MDN model=nfet_g5v0d10v5 spiceprefix=X W=5 L=1.2 nf=1 mult=24 ad=0 as=0 pd=0 ps=0 nrd=0 nrs=0}
C {devices/lab_pin.sym} -880 -180 1 0 {name=l48 lab=IREFN}
C {devices/lab_pin.sym} -920 -150 0 0 {name=l49 lab=IREFN}
C {devices/lab_pin.sym} -880 -120 3 0 {name=l50 lab=VSS}
C {devices/lab_pin.sym} -855 -150 2 0 {name=l51 lab=VSS}
N -880 -150 -855 -150 {lab=VSS}
N -920 -860 40 -860 {lab=VDD}
N -880 -830 -880 -860 {lab=VDD}
N -630 -830 -630 -860 {lab=VDD}
N -280 -630 -280 -860 {lab=VDD}
N 20 -630 20 -860 {lab=VDD}
N -920 -90 40 -90 {lab=VSS}
N -880 -120 -880 -90 {lab=VSS}
N -280 -120 -280 -90 {lab=VSS}
N 20 -120 20 -90 {lab=VSS}
N -630 -770 -630 -680 {lab=tail}
N -630 -700 -430 -700 {lab=tail}
N -430 -700 -430 -680 {lab=tail}
N -280 -570 -280 -480 {lab=pc1}
N -280 -420 -280 -330 {lab=dio}
N -280 -270 -280 -180 {lab=fn1}
N 20 -570 20 -480 {lab=pc2}
N 20 -420 20 -330 {lab=OUT}
N 20 -270 20 -180 {lab=fn2}
